Data
ScaleMode
Status
WaveformMode
typedef QMap<dataType,ClusterInfo> Data::ClusterInfoMap
friend class MinMaxThread
friend class WaveformThread
friend class CorrelationThread
friend class AutoSaveThread
friend class GroupingAssistant
friend class ClustersProvider
friend class Iterator
friend class Waveforms
friend class WaveformData< class T >
friend class Correlation
friend class SampleWaveformIterator
friend class TimeFrameWaveformIterator
friend class CorrelogramIterator
MinMaxThread* Data::minMaxThread
int Data::nbChannels
int Data::nbSamplesInWaveform
int Data::peakPositionInWaveform
QValueList<int> Data::channelIds
int Data::nbRefactorySample
int Data::RMSIntWindowLenght
float Data::firingRate
int Data::nbSampleBeforePeak
int Data::nbSampleAfterPeak
int Data::windowLenghtToRealign
int Data::peakPositionToRealign
int Data::nbFeaturesbyChannel
int Data::nbSamplesByPCA
float Data::HighPassFilterFreq
int Data::nbDimensions
long Data::nbSpikes
int Data::lowPassFilterFreq
double Data::samplingInterval
Sampling rate (time between two samples) in micro seconds.
int Data::samplingRate
int Data::nbTotalElectrodes
int Data::nbBits
QString Data::spkFileName
int Data::voltageRange
int Data::amplification
int Data::initialOffset
int Data::totalNbChannels
bool Data::traceViewVariablesAvailable
QValueList<int> Data::currentChannels
Array<dataType> Data::features
A array which contains the features for each spike: the principal componants the Valley to peak amplitude the peak to valley amplitude the max of the to previous data the width of the spike the time of the spike.
Referenced by Data::Iterator::operator().
SortableTable* Data::spikesByCluster
A two line array which contains sorted by cluster numbers and then by time: the row index of the spike in features the id of the cluster.
Referenced by Data::Iterator::operator().
QPtrList<SortableTable> Data::spikesByClusterUndoList
Represents a list of clusterInfoMap use to enable undo action.
QPtrList<SortableTable> Data::spikesByClusterRedoList
Represents a list of clusterInfoMap use to enable redo action.
ClusterInfoMap* Data::clusterInfoMap
Contains ClusterInfo key: cluster number value: a ClusterInfo (which gives: the index of the first spike in spikesByCluster and the number of spikes for a given cluster).
QPtrList<ClusterInfoMap> Data::clusterInfoMapUndoList
Represents a list of clusterInfoMap use to enable undo action.
QPtrList<ClusterInfoMap> Data::clusterInfoMapRedoList
Represents a list of clusterInfoMap use to enable redo action.
Array<dataType> Data::dimensionMaxima
List of the maximum of each dimension.
Array<dataType> Data::dimensionMinima
List of the minimum of each dimension.
QValueList<int> Data::clustersGivingMaximum
List of the clusters giving the maximum of each dimension (sorted by dimension).
QValueList<int> Data::clustersGivingMinimum
List of the clusters giving the minimum of each dimension (sorted by dimension).
QMutex Data::mutex
QT object providing access serialization between threads.
QValueList<bool> Data::dimensionChangedUndo
List containing the the dimension change status of each action of the undo list.
QValueList<bool> Data::dimensionChangedRedo
List containing the the dimension change status of each action of the redo list.
bool Data::isTwoBytesRecording
True is the data where recording using a 12 or 16 bits recording system which gives data coded on 2 bytes, false otherwise (the recording is then assume to be 32 bits and then the data are coded on 4 bytes.
QMap<int,WaveformStatus> Data::waveformStatusMap
Map containing the waveform status by cluster.
Only the clusters for which information have been asked are present in this map.
QDict<Waveforms> Data::waveformDict
Dictionary containing the waveform data by cluster.
Only the clusters for which data have been asked are present in this dictionary.
bool Data::undoRedoInProcess
Boolean use to inform the MinMaxThread that an undo or a redo is in process and that it has to stop.
bool Data::clusterZeroJustModified
Boolean use to inform the MinMaxThread that the cluster 0 has changed and that it has to stop.
CorrelationsInProcess Data::correlationsInProcess
Stores the information to know which cluster has correlations in process.
QDict< QDict<Correlation> > Data::correlationDict
Dict containing the correlations.
Key: a string representing the pair of clusters (id1-id2). The first value of the pair is always the bigger (the correlograms are calculated stored only for (A,B) with A > B and not for (B,A). value: a qdict containing a pair as a key and a Correlation object as a value. The pair represent the the bin size and the time window of the Correlation object.
SortableTable Data::reclusteringSpikesByCluster
Excerpt of spikesByCluster for the clusters selected to be recluster.
QMap<int,ClusterUserInformation> Data::clusterUserInformationMap
Map given the cluster user information, the key is the cluster id and the value an instance of ClusterUserInformation.
This map is only used to store the data read from or write to the parameter file (xml).
Data::Data()
Data::~Data()
bool Data::loadFeatures(FILE *featureFile, QString &errorInformation)
Loads the features in data.
featureFile the .fet file errorInformation string which, in case of an error, will contain detail about it. true if the loading succed false otherwise
bool Data::loadClusters(FILE *clusterFile, long spkFileLength, QString &errorInformation)
Loads the clusters in spikesByCluster.
clusterFile the .clu.i file. spkFileLength the length of the .spk.i file. errorInformation string which, in case of an error, will contain detail about it. true if the loading succed false otherwise.
bool Data::configure(QFile &parXFile, QFile &parFile, QString &errorInformation)
Loads the configuration parameters.
parXFile the .par.i file parFile the .par file errorInformation string which, in case of an error, will contain detail about it. true if the loading succed false otherwise.
bool Data::configure(QFile &parFile, int electrodeGroupID, QString &errorInformation)
Loads the configuration parameters from the xml format parameter file.
parFile the .xml parameter file. electrodeGroupID the id of the electrode group currently opened. errorInformation string which, in case of an error, will contain detail about it. true if the loading succed false otherwise.
bool Data::initialize(FILE *featureFile, long spkFileLength, QString spkFileName, QFile &parXFile, QFile &parFile, QString &errorInformation)
Load the features data, cluster data and configuration data when the cluster file does not exist.
Initialize the internal representation of the data. featureFile the .fet file spkFileLength the length of the .spk.i file spkFileName the name of the .spk.i file parXFile the .par.i file parFile the .par file errorInformation string which, in case of an error, will contain detail about it. true if the initialization succeded false otherwise
bool Data::initialize(FILE *featureFile, FILE *clusterFile, long spkFileLength, QString spkFileName, QFile &parXFile, QFile &parFile, QString &errorInformation)
Load the features data, cluster data and configuration data.
Initialize the internal representation of the data. featureFile the .fet file clusterFile the .clu.i file spkFileLength the length of the .spk.i file spkFileName the name of the .spk.i file parXFile the .par.i file parFile the .par file errorInformation string which, in case of an error, will contain detail about it. true if the initialization succeded false otherwise
bool Data::initialize(FILE *featureFile, long spkFileLength, QString spkFileName, QFile &parFile, int electrodeGroupID, QString &errorInformation)
Load the features data, cluster data and configuration data when the cluster file does not exist.
Initialize the internal representation of the data. featureFile the .fet file spkFileLength the length of the .spk.i file spkFileName the name of the .spk.i file parFile the .xml parameter file electrodeGroupID the id of the electrode group currently opened. errorInformation string which, in case of an error, will contain detail about it. true if the initialization succeded false otherwise
bool Data::initialize(FILE *featureFile, FILE *clusterFile, long spkFileLength, QString spkFileName, QFile &parFile, int electrodeGroupID, QString &errorInformation)
Load the features data, cluster data and configuration data.
Initialize the internal representation of the data. featureFile the .fet file clusterFile the .clu.i file spkFileLength the length of the .spk.i file spkFileName the name of the .spk.i file parFile the .xml parameter file electrodeGroupID the id of the electrode group currently opened. errorInformation string which, in case of an error, will contain detail about it. true if the initialization succeded false otherwise
void Data::minMaxDimensionCalculation(QValueList< int > modifiedClusters)
Calculate the minimum and maximum for each dimension and store them in dimensionMinima and dimensionMaxima respectively.
modifiedClusters list of the clusters which have been modified implying the modification of the cluster 0 this the recalculation of the minima and maxima.
dataType Data::createNewCluster(QRegion &region, const QValueList< int > &clustersOfOrigin, int dimensionX, int dimensionY, QValueList< int > &fromClusters, QValueList< int > &emptyClusters)
Creates a new cluster out of existing ones.
region the polygon defining the area containing the spikes for the new cluster. clustersOfOrigin a list of the cluster numbers identifying the clusters which may contain spikes in the region dimensionX the dimension used as absciss to display the clusters dimensionY the dimension used as ordinate to display the clusters fromClusters an empty list used as a return value, which will be filled with the cluster numbers which really contained spikes in the region emptyClusters an empty list used as a return value, which will be filled with the cluster numbers which became empty because all their spikes were put in the new one. the number of the newly created cluster or 0 if no cluster have been created (no spikes selected). This is safe as cluster 0 (artifact) can never be created that way.
QMap< int, int > Data::createNewClusters(QRegion &region, const QValueList< int > &clustersOfOrigin, int dimensionX, int dimensionY, QValueList< int > &emptyClusters)
Creates a new clusters out of existing ones.
If the polygon of selection contains x clusters x new clusters will be created. region the polygon defining the area containing the spikes for the new cluster. clustersOfOrigin a list of the cluster numbers identifying the clusters which may contain spikes in the region dimensionX the dimension used as absciss to display the clusters dimensionY the dimension used as ordinate to display the clusters emptyClusters an empty list used as a return value, which will be filled with the cluster numbers which became empty because all their spikes were put in the new one. a map where the keys are ids of the clusters which really contained spikes in the region and the values are the ids of the newly created clusters.
void Data::deleteSpikesFromClusters(QRegion &region, const QValueList< int > &clustersOfOrigin, int destinationCluster, int dimensionX, int dimensionY, QValueList< int > &fromClusters, QValueList< int > &emptyClusters)
Removes spikes from some clusters and assign them to the cluster destinationCluster which is either the cluster 0, corresponding to the artifact, or the cluster 1, corresponding to the noise.
region the polygon defining the area containing the spikes corresponding to the noise. clustersOfOrigin a list of the cluster numbers (in ascending order) identifying the clusters which may contain spikes in the region destinationCluster the cluster number to assign the spikes contained in the region fromClusters an empty list used as a return value, which will be filled with the cluster numbers which really contained spikes in the region dimensionX the dimension used as absciss to display the clusters dimensionY the dimension used as ordinate to display the clusters emptyClusters an empty list used as a return value, which will be filled with the cluster numbers which became empty because all their spikes were put in the new one.
void Data::moveClustersToNoise(QValueList< int > &clustersToDelete)
Deletes the clusters contained in clustersToDelete.
The correponding spikes are assign to cluster 1 (the noise) clustersToDelete a list of the cluster numbers (in ascending order) identifying the clusters to delete.
void Data::moveClustersToArtefact(QValueList< int > &clustersToDelete)
Deletes the clusters contained in clustersToDelete.
The correponding spikes are assign to cluster 0 (the artifact) clustersToDelete a list of the cluster numbers (in ascending order) identifying the clusters to delete.
dataType Data::groupClusters(QValueList< int > &clustersToGroup)
Groups the clusters contained in clustersToGroup.
The correponding spikes are assign to a new cluster. The user information of the different clusters to be grouped will be concatenated. clustersToGroup a list of the cluster numbers (in ascending order) identifying the clusters to group the number of the newly created cluster.
int Data::nbOfDimensions()
Returns the number of dimensions of the data.
Referenced by KlustersDoc::nbDimensions.
void Data::undo(QValueList< int > &addedClusters, QValueList< int > &updatedClusters)
Reverts the last user action.
addedClusters list of clusters which were added (can be empty). updatedClusters list of clusters which were modified (can be empty).
void Data::redo(QValueList< int > &addedClusters, QValueList< int > &updatedClusters, QValueList< int > &deletedClusters)
Reverts the last undo action.
addedClusters list of clusters which were added (can be empty). updatedClusters list of clusters which were modified (can be empty). deletedClusters list of clusters which were deleted (can be empty).
void Data::renumber(QMap< int, int > &clusterIdsOldNew, QMap< int, int > &clusterIdsNewOld)
Renumbers the clusters, so the the clusterIds will be consecutive.
clusterIdsOldNew map between old and new cluster ids. clusterIdsNewOld map between new and old cluster ids.
void Data::nbUndoChangedCleaning(int newNbUndo)
Makes all the internal changes due to a modification of the number of undo.
newNbUndo the futur new number of undo.
Iterator Data::iterator(dataType clusterId)
Creates and returns an iterator on the spikes of the given cluster.
clusterId the number of the cluster on which spikes the iterator will iterates. the iterator on the spikes of the given cluster.
QValueList<dataType> Data::clusterIds()
Returns the list of cluster Ids.
dataType Data::maxDimension(int dimension)
Returns the maximum for the dimension.
dimension for which the maximum is requested. Numbering starts at 1 maximum of the dimension
Referenced by maxTime.
dataType Data::minDimension(int dimension)
Returns the minimum for the dimension.
dimension for which the minimum is requested. Numbering starts at 1 minimum of the dimension
bool Data::saveClusters(FILE *clusterFile)
Saves the clusters information to file.
clusterFile the .clu.i file true if the data have been successfully saved to file, false otherwise.
int Data::nbOfSampleInWaveform() const
Returns the number of points used to describe a waveform.
Each point correspond to a diffrent instant in time.
int Data::positionOfPeakInWaveform() const
Returns the position of the peak among the points decribing the waveform.
int Data::nbOfchannels() const
Returns the number of channels used.
Referenced by KlustersDoc::nbOfchannels.
int Data::totalNbOfPCAs() const
Returns the total number of PCAs used (number of channels times number of PCA by channel).
Referenced by KlustersDoc::totalNbOfPCAs.
double Data::intervalOfSampling() const
Returns the sampling interval (time between two samples) in second.
int Data::timeDimension() const
Returns the dimension for the time.
long Data::maxTime()
Returns the maximum value for the time dimension in seconds.
References maxDimension.
Referenced by KlustersDoc::maxTime.
bool Data::isRecordingTwoBytes()
Gives information on how the data were recorded.
True if the data where recording using a 12 or 16 bits recording system which gives data coded on 2 bytes, false otherwise, (the recording is then assume to be 32 bits and then the data are coded on 4 bytes).
bool Data::spikePositions(int clusterId, SortableTable &subsetTable)
Gets a onr row SortableTable with the spike positions for the cluster clusterId.
clusterId d of the cluster for which the spike position are search. subsetTable the array where the result of the search will be store. true if the cluster exist and the data have been retreive, false otherwise.
int Data::nbPtsBySpike()
Returns the number of points corresponding to a spike.
This equals to: nbChannels * nbSamplesInWaveform
dataType Data::nbOfSpikes(dataType clusterId)
Returns the number of spikes of the cluster.
clusterId id of the cluster for which the number of spikes is requested. the number of spikes of the cluster clusterId.
dataType Data::totalNbOfSpikes() const
Returns the total number of spikes.
the total number of spikes.
Referenced by KlustersDoc::totalNbOfSpikes.
int Data::nbOfClusters()
Returns the current number of clusters.
the number of clusters.
void Data::setUserClusterInformation(int clusterId, QString structure, QString type, QString ID, QString quality, QString notes)
Assignes to the cluster the information given by the user.
clusterId id of the cluster for which the information are given. structure structure in which the cluster is supposed to be. type type of the cluster. ID Isolation distance of the cluster. quality quality of the cluster. notes notes of any type on the cluster.
void Data::getUserClusterInformation(int clusterId, vector< QString > &clusterInformation)
Gest the cluster the information given by the user.
clusterId id of the cluster for which the information are given. array of QString containing the following information (in the following order) : structure in which the cluster is supposed to be. type of the cluster. Isolation distance of the cluster. quality of the cluster. notes of any type on the cluster.
void Data::getClusterUserInformation(int pGroup, QMap< int, ClusterUserInformation > &clusterUserInformationMap) const
Gets the map of cluster user information.
pGroup the current electrod group id. clusterUserInformationMap map given the cluster user information, the key is the cluster id and the value an instance of ClusterUserInformation.
void Data::createFeatureFile(QValueList< int > &clustersToRecluster, QFile &fetFile)
Creates the feature file to automatically recluster the clusters contained in clustersToRecluster.
clustersToRecluster list of clusters to recluster. fetFile file to which the data will be saved.
bool Data::integrateReclusteredClusters(QValueList< int > &clustersToRecluster, QValueList< int > &reclusteredClusterList, FILE *clusterFile)
Integrates the clusters obtained by automatic reclustering.
Suppress the reclustered ones and add the newly created ones. clustersToRecluster list of clusters reclustered. reclusteredClusterList output parameter, the list of the newly created clusters. The list will be empty if the integration is not successful. clusterFile cluster file created by the automatic reclustering program. true if the integration is successful, false otherwise.
bool Data::isTraceViewVariablesAvailable() const
Informs if the the variables need it by the traceView are available.
Those variables are retrieve only from the parameter file in xml format (the new for true if the variables are available, false otherwise.
Referenced by KlustersDoc::isTraceViewVariablesAvailable.
int Data::getResolution() const
Returns the acquisition system resolution.
int Data::getTotalNbChannels() const
Returns the total number of channels used during the recording.
int Data::getSamplingRate() const
Returns the sampling rate in microseconds.
int Data::getVoltageRange() const
Returns the acquisition system voltage range.
int Data::getOffset() const
Returns the acquisition system offset.
int Data::getAmplification() const
Returns the acquisition system amplification.
int Data::getNbSamplesInWaveform() const
Returns the number of samples used to describe a waveform.
Referenced by KlustersDoc::getNbSamplesAfterPeak.
int Data::getPeakPositionInWaveform() const
Returns the sample index of the peak.
Referenced by KlustersDoc::getNbSamplesAfterPeak, KlustersDoc::getNbSamplesBeforePeak.
QValueList<int>& Data::getCurrentChannels()
Returns the list of channels of the current electrode.
Referenced by KlustersDoc::getCurrentChannels.
SampleWaveformIterator* Data::sampleWaveformIterator(dataType clusterId, dataType nbSampleSpikes)
Creates and returns an sampleWaveformIterator on the spikes of the given cluster with the specified nbSampleSpikes number of spikes.
This iterator iterates on the spikes selected for the sample mode presentation of the waveforms. In that mode, only a sample of the spikes evenly distributed on all the recording are available. clusterId the number of the cluster on which spikes the iterator will iterates. nbSampleSpikes number of spikes selected for the sample mode presentation. the sampleWaveformIterator on the spikes of the given cluster.
TimeFrameWaveformIterator* Data::timeFrameWaveformIterator(dataType clusterId, dataType startTime, dataType endTime)
Creates and returns an TimeFrameWaveformIterator on the spikes of the given cluster.
This iterator iterates on the spikes selected for the time frame mode presentation of the waveforms. In that mode, all the spikes in a given time frame are available. clusterId the number of the cluster on which spikes the iterator will iterates. startTime starting time selected for the time frame mode. endTime ending time selected for the time frame mode. the TimeFrameWaveformIterator on the spikes of the given cluster.
Data::Status Data::getCorrelograms(Pair &pair, int binSize, int timeWindow, double binSizeInRU, float timeWindowInRU, int halfBins)
Calculates the correlograms for each pair of clusters given in pairs.
pair pair of clusters for which a correlogram has to be compute. binSize size of the bins to compute given in miliseconds. timeWindow time frame use to compute the correlograms, given in miliseconds. binSizeInRU size of the bins to compute given in recording units. timeWindowInRU half of the time frame use to compute the correlograms, given in recording units. halfBins the number of bins to compute are so there are a total of nBins = 1+2*halfBins bins (halfBins.5 for each halfTimeWindow). the status, READY if the data have already been calculated or the asked computation is finish, and IN_PROCESS if an other thread is already treating the pairs the thread has to do.
CorrelogramIterator Data::correlogramIterator(Pair pair, ScaleMode scale, int binSize, int timeframe)
Creates and returns an iterator on the correlogram data of the given pair of clusters (pair).
pair the pair of clusters on which correlogram data the iterator will iterates. scale the scale to applied to the correlogram's data (maximum value, shoulder value or no scale). binSize size of the bin used to compute the correlogram. timeframe time frame used to compute the correlogram. the iterator on the correlogram data of the given pair.
bool Data::loadReclusteredClusters(FILE *clusterFile)
Loads the clusters created by the automatic reclustering program.
clusterFile the cluster file created by the automatic reclustering program. true if the loading succed false otherwise
bool Data::initialize(FILE *featureFile, long spkFileLength, QString &errorInformation)
Load the features data and configuration data when the cluster file does not exist.
Initialize the internal representation of the data. featureFile the .fet file spkFileLength the length of the .spk.i file errorInformation string which, in case of an error, will contain detail about it. true if the initialization succeded false otherwise
bool Data::initialize(FILE *featureFile, FILE *clusterFile, long spkFileLength, QString &errorInformation)
Load the features data, cluster data and configuration data.
Initialize the internal representation of the data. featureFile the .fet file clusterFile the .clu.i file spkFileLength the length of the .spk.i file errorInformation string which, in case of an error, will contain detail about it. true if the initialization succeded false otherwise
void Data::prepareUndo(SortableTable *spikesByClusterTemp, ClusterInfoMap *clusterInfoMapTemp)
Fills the undo lists (spikesByClusterUndoList,clusterInfoMapUndoList) to prepare for a futur undo.
spikesByClusterTemp the newly created spikesByCluster array clusterInfoMapTemp the newly created ClusterInfoMap map
void Data::moveClusters(QValueList< int > &clustersToDelete, SortableTable *spikesByClusterTemp, ClusterInfoMap *clusterInfoMapTemp, long upperInsertionIndex, long &nbSpikesInNewCluster, int destinationId, QValueList< long > &positions, QValueList< long > &nbOfspikes)
Moves the clusters contained in clustersToDelete to a the cluster destinationId.
The correponding spikes are assign to cluster destinationId clustersToDelete a list of the cluster numbers (in ascending order) identifying the clusters to delete. spikesByClusterTemp the new spikesByCluster which will contain the new distribution of the spikes among the clusters clusterInfoMapTemp the new clusterInfoMap which will contain the information on the new clusters upperInsertionIndex the starting position in spikesByCluster where to insert the spikes which are moved nbSpikesInNewCluster the current number of spikes in the new cluster destinationId the cluster id of destination (0 for artifact or 1for noise) positions list containing, for each cluster to delete, the position of its first spike in the new cluster's spikes (starting from the first spike of the new cluster). nbOfspikes list containing, for each cluster to delete, its number of spikes.
MinMaxThread * Data::minMaxCalculator()
Creates a new thread to calculate the min and max of the dimensions when the cluster 0 is modified.
Data::Status Data::getSampleWaveformPoints(int clusterId, dataType nbSpkToDisplay)
Gets the waveform points for cluster clusterId in the sample mode.
Take a sample of the spikes evenly distributed on all the recording. clusterId id of the cluster to get waveform information for. nbSpkToDisplay number of spikes to display. the status, READY if the data have already been collected or the current collection is finish, and IN_PROCESS if an other thread is already treating clusterId.
Data::Status Data::getTimeFrameWaveformPoints(int clusterId, dataType start, dataType end)
Gets the waveform points for cluster clusterId in time frame mode.
Take all the spikes in a given time frame. clusterId id of the cluster to get waveform information for. start starting time in second end ending time in second. the status, READY if the data have already been collected or the current collection is finish, and IN_PROCESS if an other thread is already treating that cluster.
Data::Status Data::calculateSampleMean(int clusterId, dataType nbSpkToDisplay)
Calculates the mean and the standard deviation for cluster clusterId in the sample mode.
In that mode, the spikes used are a sample of the spikes evenly distributed on all the recording. clusterId id of the cluster to calculate the data for. nbSpkToDisplay number of spikes diplayed. the status, READY if the data have already been calculated or the current calculation is finish, IN_PROCESS if an other thread is already treating that cluster and NOT_AVAILABLE if the spikes have not been collected yet.
Data::Status Data::calculateTimeFrameMean(int clusterId, dataType start, dataType end)
Calculates the mean and the standard deviation for cluster clusterId in the time frame mode.
In that mode, all the spikes in a given time frame are selected. clusterId id of the cluster to calculate the data for. start starting time in second end ending time in second. the status, READY if the data have already been calculated or the current calculation is finish, IN_PROCESS if an other thread is already treating that cluster and NOT_AVAILABLE if the spikes have not been collected yet.
void Data::cleanCorrelation(dataType clusterId, QValueList< dataType > currentClusterList, bool cleanProcess=false)
Remove all the correlations link to the cluster clusterId.
This mean remove the corresponding entries from correlationMap. clusterId id of the cluster for which the cleaning has been asked. currentClusterList list of the clusters to look for cleaning. cleanProcess true if the cluster has to be remove from correlationInProcess false otherwise. The default is false.
void Data::renumberCorrelation(QMap< int, int > &clusterIdsOldNew)
Renumber all the correlations.
clusterIdsOldNew map between old and new cluster ids.
double Data::spikeTime(SortableTable &spikesOfCluster, dataType spike)
Returns the time corresponding to a spike.
spikesOfCluster one row SortableTable corresponding to the position of the cluser's spikes in features sorted by position. spike position.
void Data::sortCluster(ClusterInfoMap *clusterInfoMapTemp, SortableTable *spikesByClusterTemp, dataType clusterId, QValueList< dataType > positions, QValueList< dataType > nbOfspikes, int step, bool fromTop=false)
Sorts by time the spikes of a newly created cluster created from other clusters, knowing that the spikes from the other clusters are already sorted.
clusterInfoMapTemp the new clusterInfoMap which will contain the information on the new clusters. spikesByClusterTemp the new spikesByCluster which will contain the new distribution of the spikes among the clusters. clusterId the id of the cluster to sort. positions list containing, for each contributing cluster, the position of either its last spike (if fromTop is false) or its first spike (if fromTop is true) in the new cluster's spikes. nbOfspikes list containing, for each contributing cluster, its number of spikes. step equals -1 if the contributing clusters are sorted from the bigger to the smaller and equals 1 if the contributing clusters are sorted from the smaller to the bigger. fromTop true if the position is given starting from the first spike of the new cluster, false if it is given starting from the last spike of the new cluster. The default is false.
void Data::sortCluster(ClusterInfoMap *clusterInfoMapTemp, SortableTable *spikesByClusterTemp, dataType clusterId, QValueList< dataType > lastPositions, QValueList< dataType > nbOfspikes, dataType firstPosition, dataType number)
Sorts by time the spikes of a newly created cluster created from other clusters.
The function is an overload of the previous one for the cases where the cluster to sort is either the cluster 0 or the cluster 1. In that case the spikes coming from those clusters are sorted from the smaller time to the bigger whereas the other clusters still sorted from the bigger to the smaller. clusterInfoMapTemp the new clusterInfoMap which will contain the information on the new clusters. spikesByClusterTemp the new spikesByCluster which will contain the new distribution of the spikes among the clusters. clusterId the id of the cluster to sort. lastPositions list containing, for each contributing cluster, the position of its last spike in the new cluster's spikes (starting from the last spike of the new cluster). nbOfspikes list containing, for each contributing cluster, tits number of spikes.e firstPosition position of the first spike of the cluster 0 or 1. number number of spikes of either the cluster 0 or 1.
long Data::findSpikePosition(double time, SortableTable &spikesOfCluster)
Finds the closest spike to a given time time among the pikes contain in spikesOfCluster.
time the time look up. spikesOfCluster array of sorted spikes in which to look up.
void Data::duplicate(SortableTable *&spikesOfClusterTemp, ClusterInfoMap *&clusterInfoMapTemp)
Makes a copy of the internal variables, spikesOfCluster and clusterInfoMap, used to store insformation about the clusters.
spikesOfClusterTemp pointer on a SortableTable which will point on a copy of the internal variable spikesOfCluster. clusterInfoMapTemp pointer on a ClusterInfoMap which will point on a copy of the internal variable clusterInfoMap.