CorrelationView
friend class CorrelationThread
Data::ScaleMode CorrelationView::scaleMode
Type of scale used, raw, scale by the maximum, or scale by the shoulder.
The default is raw mode.
QPtrList<CorrelationThread> CorrelationView::threadsToBeKill
List of pointers on the threads which have to be suppress when this object is destroy.
bool CorrelationView::dataReady
True if the correlation information needed to draw the correlograms are available.
QValueList<Pair> CorrelationView::pairs
List of pairs of clusters for which a correlogram has to be drawn.
int CorrelationView::binSize
size of the bins to use in the correlograms, given in miliseconds
int CorrelationView::timeWindow
Time frame use to compute the correlograms, given in miliseconds.
long CorrelationView::abscissaMin
Minimal abscissa in window coordinate.
long CorrelationView::abscissaMax
Maximal abscissa in window coordinate.
long CorrelationView::ordinateMin
Minimal ordinate in window coordinate.
long CorrelationView::ordinateMax
Maximal ordinate in window coordinate.
uint CorrelationView::widthBorder
The width border.
uint CorrelationView::heightBorder
The height border.
int CorrelationView::binWidth
The width of a bins.
uint CorrelationView::Xspace
Abscissa space between two correlograms.
uint CorrelationView::Yspace
Ordinate space between two correlograms.
uint CorrelationView::YsizeForMaxAmp
Size in pixels corresponding to the maximale value of a correlogram.
float CorrelationView::Yfactor
Factor use to calculate the ordinate value to been drawn.
The factor equals YsizeForMaxAmp multipled by a zoom factor.
int CorrelationView::shift
The delta between the starting abscisses of two correlograms.
int CorrelationView::nbBins
Number of bins per correlogram (2k + 1).
QValueList<Pair> CorrelationView::pairUpdateList
List of pairs corresponding to clusters to update.
bool CorrelationView::shoulderLine
Boolean indicating if a shoulder line has to be drawn on the correlograms.
float CorrelationView::tickMarkStep
Step in pixels between two tick marks.
int CorrelationView::nbTickMarks
Number of tick marks in a time window.
int CorrelationView::tickMarkZero
Abscissa of the tick mark for the center bin (time = 0).
QMap<int,QString> CorrelationView::firingRates
Map of firing rate for the autocorrelograms.
bool CorrelationView::isZoomed
True if the view has been zoomed, false ohterwise.
bool CorrelationView::goingToDie
True if the widget is about to be deleted, false otherwise.
bool CorrelationView::printState
QRegion CorrelationView::printRegion
The region representing the area to print.
const int CorrelationView::XMARGIN
Border on the left and right sides inside the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget).
const int CorrelationView::YMARGIN
Border on the top and bottom sides inside the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget).
CorrelationView::CorrelationView(KlustersDoc &doc, KlustersView &view, QColor backgroundColor, KStatusBar *statusBar, QWidget *parent=0, Data::ScaleMode scale=Data::MAX, int binSize=0, int correlationTimeFrame=0, bool shoulderLine=false, const char *name=0, int minSize=50, int maxSize=4000, int windowTopLeft=-500, int windowBottomRight=1001, int border=0)
CorrelationView::~CorrelationView()
void CorrelationView::willBeKilled()
Signals that the widget is about to be deleted.
int CorrelationView::getBinSize() const
Returns the size of the bins to use in the correlograms, given in miliseconds.
size of the bins.
int CorrelationView::getTimeWindow() const
Returns the time frame use to compute the correlograms, given in miliseconds.
time frame.
Data::ScaleMode CorrelationView::getScaleMode() const
Returns the type of scale used to present the correlation data.
type of scale.
bool CorrelationView::isShoulderLine() const
Returns a boolean indicating if a doted line is drawn at the shoulder level of the correlograms.
true if a line is drawn, false otherwise.
void CorrelationView::singleColorUpdate(int clusterId, bool active)
Updates the view only for one cluster for which the color has been changed.
clusterId cluster Id for which the color have changed. active true if the view is the active one, false otherwise.
void CorrelationView::addClusterToView(int clusterId, bool active)
Draws an additional cluster to those already shown.
This method aims to reduce the number of clusters to draw. clusterId cluster Id to add to the clusters already drawn active true if the view is the active one, false otherwise.
Referenced by addNewClusterToView.
void CorrelationView::removeClusterFromView(int clusterId, bool active)
Removes a cluster from those already shown.
Which impose to redraw everything clusterId cluster Id to remove. active true if the view is the active one, false otherwise.
void CorrelationView::addNewClusterToView(QValueList< int > &fromClusters, int clusterId, bool active)
Adds a newly created cluster to those already shown.
This method aims to reduce the number of clusters to draw. fromClusters list of clusters from which the spikes of the new cluster are coming. clusterId cluster Id to add to the clusters already drawn active true if the view is the active one, false otherwise.
void CorrelationView::addNewClusterToView(int clusterId, bool active)
Adds a newly created cluster to those already shown.
This method aims to reduce the number of clusters to draw. clusterId cluster Id to add to the clusters already drawn active true if the view is the active one, false otherwise.
References addClusterToView.
void CorrelationView::spikesRemovedFromClusters(QValueList< int > &fromClusters, bool active)
Updates the content of the widget due to the removal of spikes in a cluster.
This method aims to reduce the number of clusters to draw. fromClusters list of clusters from which the spikes have been taken. active true if the view is the active one, false otherwise.
Referenced by undoUpdateClusters, updateClusters.
void CorrelationView::spikesAddedToCluster(int clusterId, bool active)
Updates the content of the widget due to the addition of spikes in a cluster.
This method aims to reduce the number of clusters to draw. clusterId cluster Id to which the spikes have been added active true if the view is the active one, false otherwise.
void CorrelationView::setMode(BaseFrame::Mode selectedMode)
Changes the current mode, call by a selection of a tool.
selectedMode new mode of drawing (selection or zoom)
void CorrelationView::setNoScale()
Sets the mode of presentation to raw mode, meaning that the value of each bin in a correlogram will be the computed value.
void CorrelationView::setMaximumScale()
Sets the mode of presentation to raw mode, meaning that the value of each bin in a correlogram will be the computed value scale by the maximum value.
void CorrelationView::setShoulderScale()
Sets the mode of presentation to raw mode, meaning that the value of each bin in a correlogram will be the computed value scale by the shoulder value.
void CorrelationView::setBinSizeAndTimeWindow(int size, int width)
Changes the size of the bins and the size of the time frame used to compute the correlograms.
void CorrelationView::increaseAmplitude()
Increase of the amplitude of the correlograms.
void CorrelationView::decreaseAmplitude()
Decrease of the amplitude of the correlograms.
bool CorrelationView::isThreadsRunning()
Enables the caller to know if there is any thread running launch by the view.
void CorrelationView::undoUpdateClusters(QValueList< int > &modifiedClusters, bool active)
Update the clusters which have been modified by the suppression of spikes (used to create a new cluster or simply move to the cluster of noise or artefact).
This method is call only during an undo otherwise the updateClusters is call. There are 2 functions in order to reduce the number of clusters to draw whenever possible. modifiedClusters list of clusters from which spikes were taken from. active true if the view is the active one, false otherwise.
References spikesRemovedFromClusters.
void CorrelationView::updateClusters(QValueList< int > &modifiedClusters, bool active, bool isModifiedByDeletion)
Update the clusters which have been modified by the suppression of spikes (used to create a new cluster or simply move to the cluster of noise or artefact).
This method aims to reduce the number of clusters to draw. modifiedClusters list of clusters from which spikes were taken from. active true if the view is the active one, false otherwise. isModifiedByDeletion true if the clusters of modifiedClusters have been modified by the deletion of spikes (moved to cluster 0 or 1, cluster of artefact and cluster of noise respectively).
References spikesRemovedFromClusters.
void CorrelationView::setShoulderLine(bool b)
Update the presentation of a doted line at the shoulder level.
If b is true a line will be drawn, none will be drawn otherwise. b boolean indicating if a shoulder line has to be drawn.
void CorrelationView::updateDrawing()
Update the information presented in the view if need it.
void CorrelationView::clustersRenumbered(bool active)
Update the information presented in the view after a renumbering if need it.
active true if the view is the active one, false otherwise.
void CorrelationView::print(QPainter &printPainter, QPaintDeviceMetrics &metrics, bool whiteBackground)
Prints the currently display information on a printer via the painter printPainter.
printPainter painter on a printer. metrics object providing information about the printer. whiteBackground true if the printed background has to be white, false otherwise.
void CorrelationView::drawContents(QPainter *p)
Draws the contents of the frame.
p painter used to draw the contents
void CorrelationView::customEvent(QCustomEvent *event)
Treat the events sent by the CorrelationThread instances.
event custom event.
void CorrelationView::mouseDoubleClickEvent(QMouseEvent *event)
The view responds to a double click.
The correlograms are retrieve in case the data have changed (an other view has changed its parameters) as all the views are sharing the same data. event mouse event.
void CorrelationView::mouseReleaseEvent(QMouseEvent *event)
The view responds to a mouse click.
The correlograms are retrieve in case the data have changed (an other view has chaneg its parameters. event mouse release event.
void CorrelationView::resizeEvent(QResizeEvent *event)
The view responds to a resize event.
The correlograms are retrieve in case the data have changed (an other view has changed its parameters) as all the views are sharing the same data. event resize event.
void CorrelationView::mouseMoveEvent(QMouseEvent *event)
The view responds to a mouse move event.
The time is display in the status bar. event mouse move event.
CorrelationThread * CorrelationView::getCorrelations(QValueList< Pair > *pairsToCompute, QValueList< int > clusterIds)
Creates a thread which will get the correlations information for the pairs of clusters contained in pairsToCompute due to the clusters in clusterIds.
pairsToCompute couple of clusters for which a correlogram has to be obtained. clusterIds clusters for which the correlograms will be computed.
void CorrelationView::drawCorrelograms(QPainter &painter, QValueList< Pair > &pairList)
Draws the correlograms of the pair of clusters in the list pairList on the given painter.
painter painter on which to draw the correlograms. pairList list of pair of clusters for which a correlogram has to be drawn.
void CorrelationView::updateWindow()
Updates the dimension of the window.
void CorrelationView::askForCorrelograms()
Asks the correlograms for all the clusters currently shown by launching a CorrelationThread.
void CorrelationView::drawClusterIds(QPainter &painter)
Draws the clusters identifiers.
painter painter on which to draw the information.