TraceWidget
long TraceWidget::timeWindow
Amount of time used when looking for the traces.
This amount is in miliseconds and the default is 1000.
TraceView TraceWidget::view
TraceView used to actually display the traces.
long TraceWidget::startTime
Starting time when looking for the traces.
This amount is in miliseconds and the default is 0.
QSpinBox* TraceWidget::startMinute
Spine box enabling to choose the start time in minutes used to display the traces.
QSpinBox* TraceWidget::startSecond
Spine box enabling to choose the start time in seconds used to display the traces.
QSpinBox* TraceWidget::startMilisecond
Spine box enabling to choose the start time in miliseconds used to display the traces.
QLineEdit* TraceWidget::duration
Small box where the user can enter the width of the time frame to use to display the traces.
QIntValidator TraceWidget::validator
QLabel* TraceWidget::durationLabel
QLabel* TraceWidget::startLabel
bool TraceWidget::isInit
Boolean used to prevent the trigger of changes during initialization.
QScrollBar* TraceWidget::scrollBar
long long TraceWidget::recordingLength
Length of the recording in miliseconds.
long TraceWidget::lineStep
ScrollBar line step size in miliseconds.
long TraceWidget::pageStep
ScrollBar page step size in miliseconds.
QHBox* TraceWidget::selectionWidgets
Container for the selection widget.
int TraceWidget::minutePart
When converting the recording length in minutes, seconds and miliseconds this represents the number of minutes.
int TraceWidget::secondPart
When converting the recording length in minutes, seconds and miliseconds this represents the number of seconds.
int TraceWidget::milisecondPart
When converting the recording length in minutes, seconds and miliseconds this represents the number of miliseconds.
bool TraceWidget::updateView
True if the TraceView has to be updated, false otherwise.
const QString TraceWidget::INITIAL_TRACES_TIME_WINDOW
TraceWidget::TraceWidget(long startTime, long duration, bool greyScale, TracesProvider &tracesProvider, bool multiColumns, bool verticalLines, bool raster, bool waveforms, bool labelsDisplay, QValueList< int > &channelsToDisplay, int gain, int acquisitionGain, ChannelColors *channelColors, QMap< int, QValueList< int > > *groupsChannels, QMap< int, int > *channelsGroups, QValueList< int > &channelOffsets, QValueList< int > &gains, const QValueList< int > &skippedChannels, QWidget *parent=0, const char *name=0, QColor backgroundColor=Qt::black, KStatusBar *statusBar=0L, int minSize=0, int maxSize=4000, int windowTopLeft=-500, int windowBottomRight=1001, int border=0)
startTime starting time in miliseconds.
duration time window in miliseconds. greyScale true if all the channels are display either in a gradation of grey false if they are display in color. tracesProvider a reference on the provider of the channels data. multiColumns true if the traces are displayed on multiple columns, false otherwise. verticalLines true if vertical lines are displayed to show the clusters, false otherwise. raster true if a raster is drawn to show the clusters, false otherwise waveforms true if waveforms are drawn on top of the traces, false otherwise. labelsDisplay true if labels are drawn next to the traces, false otherwise. channelsToDisplay a reference on the list of channel to be shown at the opening of the view. gain initial gain use to draw the traces in the TraceView. acquisitionGain acquisition gain. channelColors a pointer on the list of colors for the channels. groupsChannels a pointer on the map given the list of channels for each group. channelsGroups a pointer on the map given to which group each channel belongs. channelOffsets a reference on the list containing the offset for each channel. gains a reference on the list of the exponents used to compute the drawing gain for each channel. skippedChannels list of skipped channels. parent the parent QWidget. name name of the widget (can be used for introspection). backgroundColor color used as background. statusBar a reference to the application status bar. minSize minumum size of the view. maxSize maximum size of the view. windowTopLeft the top-left corner of the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget). windowBottomRight bottom-right corner of the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget). border size of the border between the frame and the contents.
TraceWidget::~TraceWidget()
long TraceWidget::timeFrameWidth() const
Returns the time amount, in milisecond, of the time frame used by the TraceView.
long TraceWidget::timeFrameStart() const
Returns the start time of the time frame used by the TraceView.
void TraceWidget::installEventFilter(const QObject *filterObject)
Installs the event filter on the view contained in the widget.
void TraceWidget::changeBackgroundColor(QColor color)
void TraceWidget::setGreyScale(bool grey)
All the channels are now display either in a gradation of grey or in color.
grey true if the channels have to be displayed in grey false otherwise.
void TraceWidget::moveToTime(long time)
Display the traces starting at the given time in miliseconds.
The selection widgets are updated accordingly. time starting time to display the traces.
void TraceWidget::setMultiColumns(bool multiple)
Sets the mode of presentation to single or multiple columns.
multiple true if the traces are presented on multiple columns, false if they are presented on a single column.
References TraceView::setMultiColumns.
void TraceWidget::setClusterVerticalLines(bool lines)
Displays or hides vertical lines to show the clusters.
lines true if the vertical lines are drawn for each cluster, false otherwise.
References TraceView::setClusterVerticalLines.
void TraceWidget::setClusterRaster(bool raster)
Displays or hides a raster to show the clusters.
raster true if a raster is drawn, false otherwise.
References TraceView::setClusterRaster.
void TraceWidget::setClusterWaveforms(bool waveforms)
Displays or hides the cluster waveforms on top of the traces.
waveforms true if the waveforms are drawn, false otherwise.
References TraceView::setClusterWaveforms.
void TraceWidget::slotChannelsSelected(const QValueList< int > &selectedIds)
Informs listener that the channels selectedIds have been selected.
the list of channels selected by the user in a view.
virtual void TraceWidget::setMode(BaseFrame::Mode selectedMode, bool active)
Change the current mode, call by a selection of a tool.
selectedMode new mode of drawing. active true if the view is the active one, false otherwise.
References TraceView::setMode.
void TraceWidget::showChannels(const QValueList< int > &channelsToShow)
Updates the list of channels shown with channelsToShow.
channelsToShow new list of channels to be shown.
References TraceView::showChannels.
void TraceWidget::showClusters(QString name, QValueList< int > &clustersToShow)
Updates the list of clusters shown with clustersToShow for the cluster provider identified by name.
name name use to identified the cluster provider containing the clusters to show. clustersToShow new list of clusters to be shown.
References TraceView::showClusters.
void TraceWidget::showEvents(QString name, QValueList< int > &eventsToShow)
Updates the list of events shown with eventsToShow for the event provider identified by name.
name name use to identified the event provider containing the events to show. eventsToShow new list of events to be shown.
References TraceView::showEvents.
void TraceWidget::channelColorUpdate(int channelId, bool active)
Changes the color of a channel.
channelId id of the channel to redraw. active true if the view is the active one, false otherwise.
References TraceView::channelColorUpdate.
void TraceWidget::clusterColorUpdate(QString name, int clusterId, bool active)
Changes the color of a cluster.
name name use to identified the cluster provider containing the updated cluster. clusterId id of the cluster to redraw. active true if the view is the active one, false otherwise.
References TraceView::clusterColorUpdate.
void TraceWidget::eventColorUpdate(QString name, int eventId, bool active)
Changes the color of a event.
name name use to identified the event provider containing the updated event. eventId id of the event to redraw. active true if the view is the active one, false otherwise.
References TraceView::eventColorUpdate.
void TraceWidget::groupColorUpdate(int groupId, bool active)
Changes the color of a group of channels.
groupId id of the group for which the color have been changed. active true if the view is the active one, false otherwise.
References TraceView::groupColorUpdate.
void TraceWidget::increaseAllChannelsAmplitude()
Triggers the increase of the amplitude of all the channels.
References TraceView::increaseAllAmplitude.
void TraceWidget::decreaseAllChannelsAmplitude()
Triggers the decrease of the amplitude of all the channels.
References TraceView::decreaseAllAmplitude.
void TraceWidget::increaseSelectedChannelsAmplitude(const QValueList< int > &channelIds)
Triggers the increase of the amplitude of the selected channels.
channelIds ids of the channels for which the amplitude has to be increased.
References TraceView::increaseSelectedChannelsAmplitude.
void TraceWidget::decreaseSelectedChannelsAmplitude(const QValueList< int > &channelIds)
Triggers the decrease of the amplitude of the selected channels.
channelIds ids of the channels for which the amplitude has to be decreased.
References TraceView::decreaseSelectedChannelsAmplitude.
void TraceWidget::setGains(int gain, int acquisitionGain)
Sets the unit gain and the acquisition system gain.
gain initial gain use to draw the traces in the TraceView. acquisitionGain acquisition gain.
References TraceView::setGains.
void TraceWidget::updateDrawing()
Update the information presented in the view if need it.
References TraceView::updateDrawing.
void TraceWidget::updateContents()
Update the TraceView.
void TraceWidget::groupsModified(bool active)
Triggers the update of the display due to a change in the display groups.
active true if the view is the active one, false otherwise.
References TraceView::groupsModified.
void TraceWidget::selectChannels(const QValueList< int > &selectedIds)
Selects the channels in the TraceView.
selectedIds ids of the selected channels.
References TraceView::selectChannels.
void TraceWidget::resetOffsets(const QMap< int, int > &selectedChannelDefaultOffsets)
Resets the offset of the selected channels to the default values.
selectedChannelDefaultOffsets map given the default offsets for the selected channels.
References TraceView::resetOffsets.
void TraceWidget::resetGains(const QValueList< int > &selectedChannels)
Resets the gain of the selected channels.
selectedChannels ids of the selected channels.
References TraceView::resetGains.
void TraceWidget::drawTraces()
Informs the view to update the traces for the current time frame.
References TraceView::displayTimeFrame.
void TraceWidget::reset()
Informs the view to reset its state.
References TraceView::reset.
void TraceWidget::showLabels(bool show)
Informs the view to show or hide the labels display next to the traces.
show true if the labels have to be shown, false otherwise.
References TraceView::showHideLabels.
void TraceWidget::slotSetStartAndDuration(long time, long duration)
Displays the traces starting at the given time time in miliseconds and for the given duration duration.
The selection widgets are updated accordingly. time starting time to display the traces. duration amount of time for which to display the traces.
void TraceWidget::showCalibration(bool show, bool active)
Shows or hides the calibration bar.
This bar is meaningful only when all the channels have the same amplification. show true if the bar has to be shown false otherwise. active true if the view is the active one, false otherwise.
References TraceView::showCalibration.
void TraceWidget::samplingRateModified(long long length)
Updates the different time selection widgets due to a modification of the sampling rate for the document.
Informs the view to update the traces. length the newly computed length of the document.
void TraceWidget::addClusterProvider(ClustersProvider *clustersProvider, QString name, ItemColors *clusterColors, bool active, QValueList< int > &clustersToShow, QMap< int, QValueList< int > > *displayGroupsClusterFile, QMap< int, int > *channelsSpikeGroups, int nbSamplesBefore, int nbSamplesAfter, const QValueList< int > &clustersToSkip)
Adds a new provider of cluster data.
clustersProvider provider of cluster data. name name use to identified the cluster provider. clusterColors list of colors for the clusters. active true if the view is the active one, false otherwise. clustersToShow list of clusters to be shown. displayGroupsClusterFile map between the anatomatical groups and the cluster files. channelsSpikeGroups map between the channel ids and the spike group ids. nbSamplesBefore number of samples before the sample of the peak are contained in the waveform of a spike. nbSamplesAfter number of samples after the sample of the peak are contained in the waveform of a spike. clustersToSkip list of clusters to not use while browsing.
References TraceView::addClusterProvider.
void TraceWidget::removeClusterProvider(QString name, bool active)
Removes a provider of cluster data.
name name use to identified the cluster provider. active true if the view is the active one, false otherwise.
References TraceView::removeClusterProvider.
void TraceWidget::addEventProvider(EventsProvider *eventsProvider, QString name, ItemColors *eventColors, bool active, QValueList< int > &eventsToShow, const QValueList< int > &eventsToNotBrowse)
Adds a new provider of event data.
eventsProvider provider of event data. name name use to identified the event provider. eventColors list of colors for the events. active true if the view is the active one, false otherwise. eventsToShow list of clusters to be shown. eventsToNotBrowse list of events to not use while browsing.
References TraceView::addEventProvider.
void TraceWidget::removeEventProvider(QString name, bool active)
Removes a provider of event data.
name name use to identified the event provider. active true if the view is the active one, false otherwise.
References TraceView::removeEventProvider.
void TraceWidget::print(QPainter &printPainter, QPaintDeviceMetrics &metrics, QString filePath, bool whiteBackground)
Prints the current information drawn in the traceView.
printPainter painter on a printer. metrics object providing information about the printer. filePath path of the opened document. whiteBackground true if the printed background has to be white, false otherwise.
References TraceView::print.
void TraceWidget::showNextCluster()
Retrieves the next cluster.
References TraceView::showNextCluster.
void TraceWidget::showPreviousCluster()
Retrieves the previous cluster.
References TraceView::showPreviousCluster.
void TraceWidget::showNextEvent()
Retrieves the next event.
References TraceView::showNextEvent.
void TraceWidget::showPreviousEvent()
Retrieves the previous event.
References TraceView::showPreviousEvent.
void TraceWidget::slotEventModified(QString providerName, int selectedEventId, double time, double newTime)
Informs that an event has been modified.
providerName name use to identified the event provider containing the modified event. selectedEventId id of the modified event. time initial time of the modified event. newTime new time of the modified event.
References eventModified.
void TraceWidget::slotEventRemoved(QString providerName, int selectedEventId, double time)
Informs that an event has been removed.
providerName name use to identified the event provider containing the removed event. selectedEventId id of the removed event. time initial time of the removed event.
References eventRemoved.
void TraceWidget::updateEvents(bool active, QString providerName, double time, double newTime)
Updates the traceView if concerned by the modification of the event.
providerName name use to identified the event provider containing the modified event. time initial time of the modified event. newTime new time of the modified event. active true if the view is the active one, false otherwise.
References TraceView::updateEvents.
void TraceWidget::removeEvent()
Deletes the selected event.
References TraceView::removeEvent.
void TraceWidget::updateEvents(bool active, QString providerName, double time)
Updates the traceView if concerned by the modification of the event.
providerName name use to identified the event provider containing the removed event. time initial time of the removed event. active true if the view is the active one, false otherwise.
References TraceView::updateEvents.
void TraceWidget::eventToAddProperties(QString providerName, QString eventDescription)
Informs the traceView of the properties for the next event to be added.
providerName name use to identified the event provider which will contain the added event. eventDescription description of the next event to be created.
References TraceView::eventToAddProperties.
void TraceWidget::slotEventAdded(QString providerName, QString addedEventDescription, double time)
Informs that an event has been added.
providerName name use to identified the event provider containing the added event. addedEventDescription description of the added event. time time of the added event.
References eventAdded.
void TraceWidget::updateEvents(QString providerName, QValueList< int > &eventsToShow, bool active)
Updates the event data provided by providerName due to the addition of an event.
providerName name use to identified the event provider containing the modified event. eventsToShow new list of events to be shown. active true if the view is the active one, false otherwise.
References TraceView::updateEvents.
void TraceWidget::updateWaveformInformation(int nbSamplesBefore, int nbSamplesAfter, bool active)
Updates the description of a spike waveform.
nbSamplesBefore number of samples contained in the waveform of a spike before the sample of the peak. nbSamplesAfter number of samples contained in the waveform of a spike after the sample of the peak. active true if the view is the active one, false otherwise.
References TraceView::updateWaveformInformation.
void TraceWidget::updateClusterData(bool active)
Updates the cluster information presented on the display.
active true if the view is the active one, false otherwise.
References TraceView::updateClusterData.
void TraceWidget::updateNoneBrowsingEventList(QString providerName, const QValueList< int > &eventsToNotBrowse)
Updates the list of events to not use while browsing.
providerName name use to identified the event provider containing the modified event. eventsToNotBrowse new list of events to not use while browsing.
References TraceView::updateNoneBrowsingEventList.
void TraceWidget::updateNoneBrowsingClusterList(QString providerName, const QValueList< int > &clustersToNotBrowse)
Updates the list of clusters to not use while browsing.
providerName name use to identified the event provider containing the modified event. clustersToNotBrowse new list of clusters to not use while browsing.
References TraceView::updateNoneBrowsingClusterList.
virtual void TraceWidget::dockBeingClosed()
void TraceWidget::updateClusters(QString name, QValueList< int > &clustersToShow, ItemColors *clusterColors, bool active)
Updates the display due to modification of clusters provided by the cluster provider identified by name.
name name use to identified the cluster provider containing the clusters to show. clustersToShow new list of clusters to be shown. clusterColors list of colors for the clusters. active true if the view is the active one, false otherwise.
References TraceView::updateClusters.
void TraceWidget::updateSkipStatus(const QValueList< int > &skippedChannels)
Updates the list of skipped channels.
skippedChannels list of skipped channels.
References TraceView::skipStatusChanged.
void TraceWidget::channelsSelected(const QValueList< int > &selectedIds)
void TraceWidget::updateStartAndDuration(long startTime, long timeWindow)
Informs that the starting time and/or the timeWindow have changed.
startTime starting time. timeWindow time window.
void TraceWidget::eventModified(QString providerName, int selectedEventId, double time, double newTime)
Informs that an event has been modified.
providerName name use to identified the event provider containing the modified event. selectedEventId id of the modified event. time initial time of the modified event. newTime new time of the modified event.
Referenced by slotEventModified.
void TraceWidget::eventRemoved(QString providerName, int selectedEventId, double time)
Informs that an event has been removed.
providerName name use to identified the event provider containing the removed event. selectedEventId id of the removed event. time initial time of the removed event.
Referenced by slotEventRemoved.
void TraceWidget::eventAdded(QString providerName, QString addedEventDescription, double time)
Informs that an event has been added.
providerName name use to identified the event provider containing the added event. addedEventDescription description of the added event. time time of the added event.
Referenced by slotEventAdded.
void TraceWidget::parentDockBeingClosed(QWidget *viewWidget)
void TraceWidget::keyPressEvent(QKeyEvent *event)
The view responds to a key press event.
event key press event.
void TraceWidget::initSelectionWidgets()
Initializes the different time selection widgets.
void TraceWidget::correctStartTime()
Corrects the new start time which became inferior to the recordingLength due to a change in one of the selection widgets.
void TraceWidget::slotStartMinuteTimeUpdated(int start)
Informs the view to present the traces for an updated time frame.
void TraceWidget::slotStartSecondTimeUpdated(int start)
Informs the view to present the traces for an updated time frame.
void TraceWidget::slotStartMilisecondTimeUpdated(int start)
Informs the view to present the traces for an updated time frame.
void TraceWidget::slotDurationUpdated()
Update the selection widgets and informs view to present the traces for an updated time frame.
void TraceWidget::slotScrollBarUpdated()
Update the selection widgets and informs view to present the traces for an updated time frame.