WaveformView
PresentationMode
friend class WaveformThread
long WaveformView::maximumTime
The time maximum in second.
PresentationMode WaveformView::presentationMode
Mode of presentation used, spike sample or time frame.
The default is sample mode.
bool WaveformView::meanPresentation
Boolean indicating if all the waveforms, corresponding to the mode of presentation, are shown or if only the mean and the standard deviation.
bool WaveformView::overLayPresentation
Boolean indicating if the waveforms for the presented clusters have to overlay.
long WaveformView::abscissaMin
Minimal abscissa in window coordinate.
long WaveformView::abscissaMax
Maximal abscissa in window coordinate.
long WaveformView::ordinateMin
Minimal ordinate in window coordinate.
long WaveformView::ordinateMax
Maximal ordinate in window coordinate.
int WaveformView::nbSamplesInWaveform
Number of points used to describe a waveform.
int WaveformView::peakPositionInWaveform
Position of the peak among the points decribing the waveform.
int WaveformView::nbchannels
Number of electrodes used in that experiment.
int WaveformView::widthBorder
The width border.
int WaveformView::heightBorder
The height border.
int WaveformView::shift
The delta between the starting abscisses of two clusters.
int WaveformView::Xstep
Abscissa step between two points of a given spike.
int WaveformView::Xspace
Abscissa space between two clusters.
int WaveformView::Yspace
Ordinate space between two electrodes.
long WaveformView::X0
The abscissa of the system coordinate center for the channel which is presented at the top of the view.
long WaveformView::Y0
The ordinate of the system coordinate center for the channel which is presented at the top of the view.
int WaveformView::acquisitionGain
Acquisition system gain.
int WaveformView::gain
The actual gain is 0.75 raised to the power of gain times the acquisition system gain.
int WaveformView::YsizeForMaxAmp
Size in pixels corresponding to the amplitude maximal.
float WaveformView::Yfactor
Factor use to calculate the ordinate value to been drawn.
The factor equals YsizeForMaxAmp divided by gain.
int* WaveformView::channelPositions
Index positions of the channels.
long WaveformView::startTime
When the presentation mode is time frame, this variable keeps track of the current start time of the time window.
long WaveformView::endTime
When the presentation mode is time frame, this variable keeps track of the current end time of the time window.
bool WaveformView::isTwoBytesRecording
True is the data where recording using a 12 or 16 bits recording system which gives data coded on 2 bytes, false otherwise (the recording is then assume to be 32 bits and then the data are coded on 4 bytes.
QPtrList<WaveformThread> WaveformView::threadsToBeKill
List of pointers on the threads which have to be suppress when this object is destroy.
QPtrList<WaveformThread> WaveformView::threadsToDisregard
List of pointers on the threads for which the result should not be taken into account.
If a cluster is modified while a thread launch to obtain the cluster's data is running a second thread will be launch. In that case only the result of the last thread shoud be used.
bool WaveformView::dataReady
True if the waveform information needed to draw the waveforms are available.
QValueList<int> WaveformView::clustersToDisregard
List of the clusters to be disregared because they have been changed.
long WaveformView::nbSpkToDisplay
The number of spikes to display in sample mode.
bool WaveformView::isZoomed
True if the view has been zoomed, false ohterwise.
bool WaveformView::goingToDie
True if the widget is about to be deleted, false otherwise.
const int WaveformView::XMARGIN
Border on the left and right sides inside the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget).
const int WaveformView::YMARGIN
Border on the top and bottom sides inside the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget).
WaveformView::WaveformView(KlustersDoc &doc, KlustersView &view, QColor backgroundColor, int acquisitionGain, QValueList< int > positions, KStatusBar *statusBar, QWidget *parent=0, bool isTimeFrameMode=false, long start=0, long timeFrameWidth=0, long nbSpkToDisplay=0, bool overLay=false, bool mean=false, const char *name=0, int minSize=50, int maxSize=4000, int windowTopLeft=-500, int windowBottomRight=1001, int border=0)
WaveformView::~WaveformView()
void WaveformView::willBeKilled()
Signals that the widget is about to be deleted.
void WaveformView::singleColorUpdate(int clusterId, bool active)
Updates the view only for one cluster for which the color has been changed.
clusterId cluster Id for which the color have changed. active true if the view is the active one, false otherwise.
void WaveformView::addClusterToView(int clusterId, bool active)
Draws an additional cluster to those already shown.
This method aims to reduce the number of clusters to draw. clusterId cluster Id to add to the clusters already drawn active true if the view is the active one, false otherwise.
Referenced by addNewClusterToView.
void WaveformView::removeClusterFromView(int clusterId, bool active)
Removes a cluster from those already shown.
Which impose to redraw everything clusterId cluster Id to remove. active true if the view is the active one, false otherwise.
void WaveformView::addNewClusterToView(QValueList< int > &fromClusters, int clusterId, bool active)
Adds a newly created cluster to those already shown.
This method aims to reduce the number of clusters to draw. fromClusters list of clusters from which the spikes of the new cluster are coming. clusterId cluster Id to add to the clusters already drawn active true if the view is the active one, false otherwise.
void WaveformView::addNewClusterToView(int clusterId, bool active)
Adds a newly created cluster to those already shown.
This method aims to reduce the number of clusters to draw. clusterId cluster Id to add to the clusters already drawn active true if the view is the active one, false otherwise.
References addClusterToView.
void WaveformView::spikesRemovedFromClusters(QValueList< int > &fromClusters, bool active)
Updates the content of the widget due to the removal of spikes in a cluster.
This method aims to reduce the number of clusters to draw. fromClusters list of clusters from which the spikes have been taken. active true if the view is the active one, false otherwise.
Referenced by undoUpdateClusters, updateClusters.
void WaveformView::spikesAddedToCluster(int clusterId, bool active)
Updates the content of the widget due to the addition of spikes in a cluster.
This method aims to reduce the number of clusters to draw. clusterId cluster Id to which the spikes have been added active true if the view is the active one, false otherwise.
void WaveformView::setMode(BaseFrame::Mode selectedMode)
Changes the current mode, call by a selection of a tool.
selectedMode new mode of drawing (selection or zoom)
void WaveformView::updateClusters(QValueList< int > &modifiedClusters, bool active, bool isModifiedByDeletion)
Updates the clusters which have been modified by the suppression of spikes (used to create a new cluster or simply move to the cluster of noise or artefact).
This method aims to reduce the number of clusters to draw. modifiedClusters list of clusters from which spikes were taken from. active true if the view is the active one, false otherwise. isModifiedByDeletion true if the clusters of modifiedClusters have been modified by the deletion of spikes (moved to cluster 0 or 1, cluster of artefact and cluster of noise respectively).
References spikesRemovedFromClusters.
void WaveformView::undoUpdateClusters(QValueList< int > &modifiedClusters, bool active)
Updates the clusters which have been modified by the suppression of spikes (used to create a new cluster or simply move to the cluster of noise or artefact).
This method is call only during an undo otherwise the updateClusters is call. There are 2 functions in order to reduce the number of clusters to draw whenever possible. modifiedClusters list of clusters from which spikes were taken from. active true if the view is the active one, false otherwise.
References spikesRemovedFromClusters.
void WaveformView::setMeanPresentation()
Sets the way of presenting the information concerning the waveforms selected to only show the waveforms of the mean and the standard deviation.
void WaveformView::setAllWaveformsPresentation()
Sets the way of presenting the information concerning the waveforms selected to show all the waveforms corresponding to the mode of presentation.
void WaveformView::setOverLayPresentation()
The waveforms of each cluster are overlaying.
void WaveformView::setSideBySidePresentation()
The waveforms of each cluster are presented side by side.
void WaveformView::setSampleMode()
Sets the mode of presentation to sample mode, meaning that, for each shown cluster, only one out of the number of spikes to be displayed will be shown.
void WaveformView::setTimeFrameMode()
Sets the mode of presentation to time frame mode, meaning that, for each shown cluster, only the spikes within the current time frame will be shown.
void WaveformView::setTimeFrame(long start, long width)
Changes the time and update the view accordingly.
start start time of the time frame in second. width width of the time frame in second.
void WaveformView::setGain(int gain)
Sets the initial maximum amplitude of the waveforms.
gain the new value to set the initial maximum amplitude of the waveforms (before increase or decrease).
References BaseFrame::drawContentsMode.
void WaveformView::increaseAmplitude()
Increase of the amplitude of the waveforms.
void WaveformView::decreaseAmplitude()
Decrease of the amplitude of the waveforms.
void WaveformView::setDisplayNbSpikes(long nbSpikes)
Increase of the number of samples display in the sample mode.
bool WaveformView::isThreadsRunning()
Enables the caller to know if there is any thread running launch by the view.
void WaveformView::updateDrawing()
Update the information presented in the view if need it.
void WaveformView::setChannelPositions(QValueList< int > &positions)
Initialize the position of the channels in the view.
positions positions of the channels to use in the view set by the user in the settings dialog.
References BaseFrame::drawContentsMode.
void WaveformView::clustersRenumbered(bool active)
Update the information presented in the view after a renumbering if need it.
active true if the view is the active one, false otherwise.
void WaveformView::print(QPainter &printPainter, QPaintDeviceMetrics &metrics, bool whiteBackground)
Prints the currently display information on a printer via the painter printPainter.
printPainter painter on a printer. metrics object providing information about the printer. whiteBackground true if the printed background has to be white, false otherwise.
void WaveformView::drawContents(QPainter *p)
Draws the contents of the frame.
p painter used to draw the contents of the frame.
void WaveformView::customEvent(QCustomEvent *event)
Treat the events sent by the WaveformThread instances.
void WaveformView::mouseDoubleClickEvent(QMouseEvent *event)
The view responds to a double click.
The waveforms are retrieve in case the data have changed (an other view has changed its parameters) as all the views are sharing the same data. event mouse event.
void WaveformView::mouseReleaseEvent(QMouseEvent *event)
The view responds to a mouse click.
The waveforms are retrieve in case the data have changed (an other view has changed its parameters) as all the views are sharing the same data. event mouse release event.
void WaveformView::resizeEvent(QResizeEvent *event)
The view responds to a resize event.
The waveforms are retrieve in case the data have changed (an other view has changed its parameters) as all the views are sharing the same data. event resize event.
void WaveformView::drawWaveforms(QPainter &painter, const QValueList< int > &clusterList)
Draws the waveforms of the clusters in the list clustersList on the given painter.
painter painter on which to draw the waveforms clusterList list of clusters to draw
void WaveformView::updateWindow()
Updates the dimension of the window.
WaveformThread * WaveformView::getWaveforms()
Creates a thread which will get the waveform information.
void WaveformView::askForWaveformInformation(int clusterId)
Asks the waveform information for the cluster clusterId by launching a WaveformThread.
clusterId id of the cluster to ask waveform information for.
void WaveformView::askForWaveformInformation(QValueList< int > clusterIds)
Asks the waveform information for the clusters listed in clusterIds by launching a WaveformThread.
clusterIds ids of the clusters to ask waveform information for.
void WaveformView::updateClusters(QValueList< int > &clustersToUpdate)
Adds the clusters to the list of those to be updated and get the updated waveform information for it.
clustersToUpdate list of clusters to update
void WaveformView::drawClusterIds(QPainter &painter)
Draws the clusters identifiers.
painter painter on which to draw the information