TraceView
@1
bool TraceView::greyScaleMode
True if the the colors are in grey-scale.
KStatusBar* TraceView::statusBar
Pointer to the status bar of the application.
TracesProvider& TraceView::tracesProvider
Provider of the channels data.
bool TraceView::multiColumns
True if the traces are displayed on multiple columns, false otherwise.
bool TraceView::verticalLines
True if vertical lines are displayed to show the clusters, false otherwise.
bool TraceView::raster
True if a raster is drawn to show the clusters, false otherwise.
bool TraceView::waveforms
True if waveforms are drawn on top of the traces, false otherwise.
QValueList<int> TraceView::shownChannels
List of the presented channels.
bool TraceView::dataReady
True if the data information needed to draw the traces are available.
Array<dataType> TraceView::data
Array containing the traces data.
QValueList<int>& TraceView::channelOffsets
List containing the offset for each channel.
QValueList<float> TraceView::channelFactors
List of the factors use to calculate the ordinate value to been drawn.
The factor equals 0.75 raised to the power of the gain (Yworld = alpha.factor.Ydata).
QValueList<int>& TraceView::gains
List of the exponents used to compute the drawing gain for each channel.
The actual gain is 0.75 raised to the power of gain.
int TraceView::traceVspace
Size in pixels corresponding to the vertical space allocated to a trace.
int TraceView::nbChannels
Number of channels used to record the data.
int TraceView::peakPositionInWaveform
Position of the peak among the points decribing waveforms.
int TraceView::nbSamplesInWaveform
Number of points used to describe a waveform.
long TraceView::startTime
This variable keeps track of the current start time of the time window.
long TraceView::endTime
This variable keeps track of the current end time of the time window.
ChannelColors* TraceView::channelColors
Pointer on the ChannelColors storing the color information for the channels.
QMap<int, QValueList<int> >* TraceView::groupsChannels
Map the correspondence between the channel group ids and the channel ids.
Pointer to the variable belonging to NeuroscopeDoc.
QMap<int,int>* TraceView::channelsGroups
Stores to which group each channel belongs.
Pointer to the variable belonging to NeuroscopeDoc.
QMap<int, QValueList<int> > TraceView::shownGroupsChannels
Map the correspondence between the channel group ids and the channel ids for the displayed channels.
long TraceView::abscissaMin
Minimal abscissa in window coordinate.
long TraceView::abscissaMax
Maximal abscissa in window coordinate.
long TraceView::ordinateMin
Minimal ordinate in window coordinate.
long TraceView::ordinateMax
Maximal ordinate in window coordinate.
int TraceView::borderX
The border on the left and right sides.
int TraceView::borderY
The border at the top and bottom.
int TraceView::Yshift
The delta between the starting ordinates of two channels.
int TraceView::Xshift
The delta between the starting abcisses of two channels.
int TraceView::Xstep
Abscissa step between two points of a given trace.
int TraceView::XGroupSpace
Abscissa space between two groups (when groups are display on several columns).
int TraceView::Yspace
Ordinate space between two channels.
int TraceView::YGroupSpace
Ordinate space between two groups (when groups are display on a single columns).
int TraceView::YTracesRasterSeparator
Ordinate space between the traces and the raster.
int TraceView::YRasterSpace
Ordinate space between two cluster trains.
long TraceView::X0
The abscissa of the system coordinate center for the channel which is presented at the top of the view.
long TraceView::Y0
The ordinate of the system coordinate center for the channel which is presented at the top of the view.
long TraceView::Y0Raster
The ordinate for the first cluster raster.
QPixmap TraceView::doublebuffer
Buffer to enable smooth updating, obtain flicker-free drawing.
Prevent from unnecessary redrawing.
float TraceView::timeStep
Time in milisseconds corresponding to a step between two points of a given trace.
float TraceView::timeStepUnit
Time in milisseconds corresponding to a step between two samples.
int TraceView::acquisitionGain
Acquisition system gain in recording unit by milivolts.
int TraceView::unitGain
Unit gain in recording unit by centimeters.
float TraceView::alpha
Factor, in pixels by recording units, to convert the data in recording units to data in pixels of the world (Yworld = alpha.factor.Ydata).
This factor is computed using the amplitude maximal of theta and the acquisition system gain.
QValueList<float> TraceView::channelDisplayGains
List of the gains display next to each drawn channel.
int TraceView::nbClusters
int TraceView::rasterHeight
Size in pixels corresponding to the height of a raster.
long TraceView::timeFrameWidth
Time amount, in milisecond, of the time frame used to display the traces.
QMap<int,int> TraceView::channelsStartingOrdinate
Stores the ordinate of the first sample of each channel.
QMap<int,int> TraceView::channelsStartingAbscissa
Stores the abscissa of the first sample of each channel.
int TraceView::xMargin
Border on the left and right sides inside the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget).
int TraceView::yMargin
Border on the top and bottom sides inside the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget).
bool TraceView::columnDisplayChanged
Boolean used to update the display after a change in the mode of display: single or multicolumns.
bool TraceView::resized
Boolean used to update the display after a resize event.
QValueList<int> TraceView::selectedChannels
List of the selected channels.
bool TraceView::groupsChanged
Boolean used to update the display after a change in the number of groups.
int TraceView::previousDragOrdinate
Ordinate of the previous position while dragging an event.
int TraceView::lastClickOrdinate
Ordinate of the last click before dragging channels.
bool TraceView::nbSamplesModified
bool TraceView::alreadySelected
bool TraceView::isInit
Boolean used to correctly display multicolumns at startup.
int TraceView::screenResolution
Screen resolution in pixel by centimeter, the default is 30 (equivalent to 75 pixels by inch).
int TraceView::channelforVoltageComputation
Channel for which the voltage has to be determined.
int TraceView::startingIndex
Index of the starting drag, use to determine the time when selecting a zone for measure.
QCursor TraceView::selectCursor
A cursor to represent the selection of channels.
QCursor TraceView::measureCursor
A cursor to represent the measure state.
QCursor TraceView::selectTimeCursor
A cursor to represent the selection of time state.
QCursor TraceView::selectEventCursor
A cursor to represent the selection of an event.
QCursor TraceView::addEventCursor
A cursor to represent the addition of an event.
QCursor TraceView::drawLineCursor
A cursor to represent the drawing of a line.
bool TraceView::showLabels
Boolean indicating that the labels next to the traces have to be shown or hide.
If true, they have to be shown, if false they have to be hidden. They are hidden by default.
bool TraceView::showCalibrationScale
Boolean indicating that the calibration scale has to be shown or hide.
If true, the scale has to be shown, if false it has to be hidden. It is hidden by default.
float TraceView::downSampling
Number of samples to leave out while drawing in order to speed the browsing of the data.
This number takes into account the size of the window and the the size of the widget.
bool TraceView::zoomed
Boolean indicating that the view has been zoomed.
bool TraceView::firstZoom
bool TraceView::doubleClick
float TraceView::initialDownSampling
Initial downSampling before any zoom.
float TraceView::zoomFactor
Stores the current factor of zoom.
bool TraceView::maxZoomReached
bool TraceView::zoomOut
QRect TraceView::initialWindow
Initial window before any zoom.
QRect TraceView::previousWindow
Window used before the current zoom.
int TraceView::traceWidth
The current size of a trace in the world while in multi columns mode.
int TraceView::initialXGroupSpace
The initial abscissa space between two groups (when groups are display on several columns) before any zoom.
int TraceView::initialXshift
The initial delta between the starting abcisses of two channels before any zoom.
int TraceView::initialTraceWidth
The initial size of a trace in the world while in multi columns mode.
QMap<int, QValueList<int> > TraceView::selectedClusters
Map between the cluster provider names and the list of selected clusters.
QDict<ClusterData> TraceView::clustersData
Dictionary between the cluster provider names and the cluster data and status.
QDict<ClustersProvider> TraceView::clusterProviders
Dictionary between the cluster provider names and the providers.
QDict<ItemColors> TraceView::providerItemColors
Dictionary between the provider names and the item color lists except for the TracesProvider.
QValueList<QString> TraceView::clustersOrder
Stores the cluster order used when they are presented in raster.
Each cluster is identified by a string build as the ClusterProvider name plus a dash plus the cluster id.
QValueList<int> TraceView::rasterOrdinates
Stores the cluster raster ordinate position.
QValueList<int> TraceView::rasterAbscisses
Stores the cluster raster abscissa position.
QMap<int, QValueList<int> >* TraceView::groupClusterFiles
Map given the list of cluster file containing data for a given display group.
This assumes that the cluster file names contain the identifier of the spike group used to create them (myFile.clu.1 correspond to the spike group 1).
QMap<int,int>* TraceView::channelClusterFiles
int TraceView::nbSamplesBefore
int TraceView::nbSamplesAfter
bool TraceView::printState
QMap<QString, QValueList<int> > TraceView::selectedEvents
Map between the event provider names and the list of selected events.
QPair<QString,long> TraceView::nextClusterProvider
Pair storing the cluster provider having a selected cluster the closer in time to the current endTime, the pair stores also the starting time of the retrieve data.
QPair<QString,long> TraceView::previousClusterProvider
Pair storing the cluster provider having a selected cluster the closer in time to the current startTime, the pair stores also the starting time of the retrieve data.
QString TraceView::clusterProviderToSkip
Stores the cluster provider which contains the cluster id look up in a nextCluster or previousCluster action.
long TraceView::startTimeInRecordingUnits
This variable keeps track of the current start time of the time window in recording unit when browsing on the spikes.
long TraceView::previousStartTimeInRecordingUnits
This variable keeps track of the previous start time of the time window in recording unit when browsing on the spikes.
bool TraceView::spikeBrowsing
True if the user has just browsed spikes, false otherwise.
QDict<EventData> TraceView::eventsData
Dictionary between the event provider names and the event data and status.
QDict<EventsProvider> TraceView::eventProviders
Dictionary between the event provider names and the providers.
QPair<QString,long> TraceView::nextEventProvider
Pair storing the event provider having a selected event the closer in time to the current endTime, the pair stores also the starting time of the retrieve data.
QPair<QString,long> TraceView::previousEventProvider
Pair storing the event provider having a selected event the closer in time to the current startTime, the pair stores also the starting time of the retrieve data.
QString TraceView::eventProviderToSkip
Stores the event provider which contains the event id look up in a nextEvent or previousEvent action.
long long TraceView::recordingLength
Length of the recording in miliseconds.
QPair<QString,int> TraceView::selectedEvent
Pair storing the event provider and the event id corresponding to the currently selected event.
int TraceView::previousDragAbscissa
Abscissa of the previous position while dragging channels.
int TraceView::lastClickAbscissa
Abscissa of the last click before dragging an event.
QValueList<int> TraceView::selectedEventPosition
Contains the original abscissa and index of the selected event.
bool TraceView::startEventDragging
True if it is the beginning of an event dragging.
QValueList<QString> TraceView::eventProvidersToUpdate
Stores the event providers containing events which have been modified and thus needing to be update.
int TraceView::newEventPosition
Index of the new event to create.
QString TraceView::eventDescriptionToCreate
Label corresponding to the type of event to create at the next addEvent.
QString TraceView::eventProvider
Identifier of the event file to which a new event will be added.
bool TraceView::eventBeingModified
Boolean indicating that the modification of an event is in process.
QMap<QString, QValueList<int> > TraceView::clustersNotUsedForBrowsing
Map between the cluster provider names and the list of clusters to not be used for browsing.
QMap<QString, QValueList<int> > TraceView::eventsNotUsedForBrowsing
Map between the event provider names and the list of events to not be used for browsing.
bool TraceView::retrieveClusterData
QValueList<int> TraceView::skippedChannels
QValueList<int> TraceView::linePositions
const int TraceView::XMARGIN
Default value for the border on the left and right sides inside the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget).
const int TraceView::YMARGIN
Default value for the border on the top and bottom sides inside the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget).
TraceView::TraceView(TracesProvider &tracesProvider, bool greyScale, bool multiColumns, bool verticalLines, bool raster, bool waveforms, bool labelsDisplay, QValueList< int > &channelsToDisplay, int unitGain, int acquisitionGain, long start, long timeFrameWidth, ChannelColors *channelColors, QMap< int, QValueList< int > > *groupsChannels, QMap< int, int > *channelsGroups, QValueList< int > &channelOffsets, QValueList< int > &gains, const QValueList< int > &skippedChannels, QWidget *parent=0, const char *name=0, QColor backgroundColor=Qt::black, KStatusBar *statusBar=0L, int minSize=500, int maxSize=4000, int windowTopLeft=-500, int windowBottomRight=1001, int border=0)
Constructor.
tracesProvider a reference on the provider of the channels data. greyScale true if all the channels are display either in a gradation of grey false if they are display in color. multiColumns true if the traces are displayed on multiple columns, false otherwise. verticalLines true if vertical lines are displayed to show the clusters, false otherwise. raster true if a raster is drawn to show the clusters, false otherwise waveforms true if waveforms are drawn on top of the traces, false otherwise. labelsDisplay true if labels are drawn next to the traces, false otherwise. channelsToDisplay a reference on the list of channel to be shown at the opening of the view. unitGain initial gain use to draw the traces. acquisitionGain acquisition gain. start starting time in miliseconds. timeFrameWidth time window in miliseconds. channelColors a pointer on the list of colors for the channels. groupsChannels a pointer on the map given the list of channels for each group. channelsGroups a pointer on the map given to which group each channel belongs. channelOffsets a reference on the list containing the offset for each channel. gains a reference on the list of the exponents used to compute the drawing gain for each channel. skippedChannels list of skipped channels. parent the parent QWidget. name name of the widget (can be used for introspection). backgroundColor color used as background. statusBar a reference to the application status bar. minSize minumum size of the view. maxSize maximum size of the view. windowTopLeft the top-left corner of the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget). windowBottomRight bottom-right corner of the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget). border size of the border between the frame and the contents.
TraceView::~TraceView()
void TraceView::setMultiColumns(bool multiple)
Sets the mode of presentation to single or multiple columns.
multiple true if the traces are presented on multiple columns, false if they are presented on a single column.
Referenced by TraceWidget::setMultiColumns.
void TraceView::setClusterVerticalLines(bool lines)
Displays or hides vertical lines to show the clusters.
lines true if the vertical lines are drawn for each cluster, false otherwise.
Referenced by TraceWidget::setClusterVerticalLines.
void TraceView::setClusterRaster(bool raster)
Displays or hides a raster to show the clusters.
raster true if a raster is drawn, false otherwise.
Referenced by TraceWidget::setClusterRaster.
void TraceView::setClusterWaveforms(bool waveforms)
Displays or hides the cluster waveforms on top of the traces.
waveforms true if the waveforms are drawn, false otherwise.
Referenced by TraceWidget::setClusterWaveforms.
void TraceView::setGreyScale(bool grey)
All the channels of the display are now display either in a gradation of grey or in color.
grey true if the channels have to be displayed in grey false otherwise.
void TraceView::displayTimeFrame(long start, long timeFrameWidth)
Updates the traces to show between start and start + timeFrameWidth.
start starting time in miliseconds. timeFrameWidth time window in miliseconds.
Referenced by TraceWidget::drawTraces.
void TraceView::showChannels(const QValueList< int > &channelsToShow)
Updates the list of channels shown with channelsToShow.
channelsToShow new list of channels to be shown.
Referenced by TraceWidget::showChannels.
void TraceView::increaseAllAmplitude()
Increases of the amplitude of all the channels.
Referenced by TraceWidget::increaseAllChannelsAmplitude.
void TraceView::decreaseAllAmplitude()
Decreases of the amplitude of all the channels.
Referenced by TraceWidget::decreaseAllChannelsAmplitude.
void TraceView::increaseSelectedChannelsAmplitude(const QValueList< int > &channelIds)
Increases of the amplitude of the selected channels.
channelIds ids of the channels for which the amplitude has to be increased.
Referenced by TraceWidget::increaseSelectedChannelsAmplitude.
void TraceView::decreaseSelectedChannelsAmplitude(const QValueList< int > &channelIds)
Decreases of the amplitude of the selected channels.
channelIds ids of the channels for which the amplitude has to be decreased.
Referenced by TraceWidget::decreaseSelectedChannelsAmplitude.
void TraceView::setGains(int gain, int acquisitionGain)
Sets the unit gain and the acquisition system gain.
gain initial gain use to draw the traces in the TraceView. acquisitionGain acquisition gain.
Referenced by TraceWidget::setGains.
void TraceView::channelColorUpdate(int channelId, bool active)
Changes the color of a channel.
channelId id of the channel to redraw. active true if the view is the active one, false otherwise.
Referenced by TraceWidget::channelColorUpdate.
void TraceView::groupColorUpdate(int groupId, bool active)
Changes the color of a group of channels.
groupId id of the group for which the color have been changed. active true if the view is the active one, false otherwise.
References BaseFrame::drawContentsMode.
Referenced by TraceWidget::groupColorUpdate.
void TraceView::updateDrawing()
Update the information presented in the view.
References BaseFrame::drawContentsMode, updateClusterData.
Referenced by TraceWidget::updateDrawing.
void TraceView::groupsModified(bool active)
Updates of the display due to a change in the display groups if active is true, otherwise simply updates the internal variables.
active true if the view is the active one, false otherwise.
Referenced by TraceWidget::groupsModified.
void TraceView::setMode(BaseFrame::Mode selectedMode, bool active)
Change the current mode, call by a selection of a tool.
selectedMode new mode of drawing. active true if the view is the active one, false otherwise.
References BaseFrame::drawContentsMode, BaseFrame::drawRubberBand, BaseFrame::mode, BaseFrame::zoomCursor.
Referenced by TraceWidget::setMode.
void TraceView::selectChannels(const QValueList< int > &selectedIds)
Selects the channels .
selectedIds ids of the selected channels.
Referenced by TraceWidget::selectChannels.
void TraceView::resetOffsets(const QMap< int, int > &selectedChannelDefaultOffsets)
Resets the offset of the selected channels to the default values.
selectedChannelDefaultOffsets map given the default offsets for the selected channels.
Referenced by TraceWidget::resetOffsets.
void TraceView::resetGains(const QValueList< int > &selectedChannels)
Resets the gain of the selected channels.
selectedChannels ids of the selected channels.
Referenced by TraceWidget::resetGains.
void TraceView::reset()
Resets the state of the view.
Referenced by TraceWidget::reset.
void TraceView::showHideLabels(bool show)
Shows or hide the labels next to the channels displaying the channel id and the gain.
show true if the labels have to be shown, false otherwise.
Referenced by TraceWidget::showLabels.
void TraceView::showCalibration(bool show, bool active)
Shows or hide the calibration scale.
show true if the scale has to be shown, false otherwise. active true if the view is the active one, false otherwise.
References BaseFrame::drawContentsMode.
Referenced by TraceWidget::showCalibration.
void TraceView::addClusterProvider(ClustersProvider *clustersProvider, QString name, ItemColors *clusterColors, bool active, QValueList< int > &clustersToShow, QMap< int, QValueList< int > > *displayGroupsClusterFile, QMap< int, int > *channelsSpikeGroups, int nbSamplesBefore, int nbSamplesAfter, const QValueList< int > &clustersToSkip)
Adds a new provider of cluster data.
clustersProvider provider of cluster data. name name use to identified the cluster provider. clusterColors list of colors for the clusters. active true if the view is the active one, false otherwise. clustersToShow list of clusters to be shown. displayGroupsClusterFile map between the anatomatical groups and the cluster files. channelsSpikeGroups map between the channel ids and the spike group ids. nbSamplesBefore number of samples contained in the waveform of a spike before the sample of the peak. nbSamplesAfter number of samples contained in the waveform of a spike after the sample of the peak. clustersToSkip list of clusters to not use while browsing.
Referenced by TraceWidget::addClusterProvider.
void TraceView::removeClusterProvider(QString name, bool active)
Removes a provider of cluster data.
name name use to identified the cluster provider. active true if the view is the active one, false otherwise.
Referenced by TraceWidget::removeClusterProvider.
void TraceView::showClusters(QString name, QValueList< int > &clustersToShow)
Updates the list of clusters shown with clustersToShow for the cluster provider identified by name.
name name use to identified the cluster provider containing the clusters to show. clustersToShow new list of clusters to be shown.
Referenced by TraceWidget::showClusters.
void TraceView::clusterColorUpdate(QString name, int clusterId, bool active)
Changes the color of a cluster.
name name use to identified the cluster provider containing the updated cluster. clusterId id of the cluster to redraw. active true if the view is the active one, false otherwise.
Referenced by TraceWidget::clusterColorUpdate.
void TraceView::addEventProvider(EventsProvider *eventsProvider, QString name, ItemColors *eventColors, bool active, QValueList< int > &eventsToShow, const QValueList< int > &eventsToSkip)
Adds a new provider of event data.
eventsProvider provider of event data. name name use to identified the event provider. eventColors list of colors for the events. active true if the view is the active one, false otherwise. eventsToShow list of events to be shown. eventsToSkip list of events to not use while browsing.
Referenced by TraceWidget::addEventProvider.
void TraceView::removeEventProvider(QString name, bool active)
Removes a provider of event data.
name name use to identified the event provider. active true if the view is the active one, false otherwise.
Referenced by TraceWidget::removeEventProvider.
void TraceView::showEvents(QString name, QValueList< int > &eventsToShow)
Updates the list of events shown with eventsToShow for the event provider identified by name.
name name use to identified the event provider containing the events to show. eventsToShow new list of events to be shown.
Referenced by TraceWidget::showEvents.
void TraceView::eventColorUpdate(QString name, int eventId, bool active)
Changes the color of a event.
name name use to identified the event provider containing the updated event. eventId id of the event to redraw. active true if the view is the active one, false otherwise.
Referenced by TraceWidget::eventColorUpdate.
void TraceView::print(QPainter &printPainter, QPaintDeviceMetrics &metrics, bool whiteBackground)
Prints the currently display information on a printer via the painter printPainter.
Does not print zoomed display. printPainter painter on a printer. metrics object providing informatin about the printer. whiteBackground true if the printed background has to be white, false otherwise.
Referenced by TraceWidget::print.
void TraceView::showNextEvent()
Retrieves the next event.
Referenced by TraceWidget::showNextEvent.
void TraceView::showPreviousEvent()
Retrieves the previous event.
Referenced by TraceWidget::showPreviousEvent.
void TraceView::updateEvents(QString providerName, bool active)
Updates the event data provided by providerName due to a modification of an event.
providerName name use to identified the event provider containing the modified event. active true if the view is the active one, false otherwise.
Referenced by TraceWidget::updateEvents.
void TraceView::updateEvents(QString providerName, QValueList< int > &eventsToShow, bool active)
Updates the event data provided by providerName due to the addition of an event.
providerName name use to identified the event provider containing the modified event. eventsToShow new list of events to be shown. active true if the view is the active one, false otherwise.
void TraceView::removeEvent()
Deletes the selected event.
Referenced by TraceWidget::removeEvent.
void TraceView::showNextCluster()
Retrieves the next cluster.
Referenced by TraceWidget::showNextCluster.
void TraceView::showPreviousCluster()
Retrieves the previous cluster.
Referenced by TraceWidget::showPreviousCluster.
void TraceView::updateNoneBrowsingEventList(QString providerName, const QValueList< int > &eventsToNotBrowse)
Updates the list of events to not use while browsing.
providerName name use to identified the event provider containing the modified event. eventsToNotBrowse new list of events to not use while browsing.
Referenced by TraceWidget::updateNoneBrowsingEventList.
void TraceView::updateNoneBrowsingClusterList(QString providerName, const QValueList< int > &clustersToNotBrowse)
Updates the list of clusters to not use while browsing.
providerName name use to identified the event provider containing the modified event. clustersToNotBrowse new list of clusters to not use while browsing.
Referenced by TraceWidget::updateNoneBrowsingClusterList.
void TraceView::updateWaveformInformation(int nbSamplesBefore, int nbSamplesAfter, bool active)
Updates the description of a spike waveform.
nbSamplesBefore number of samples contained in the waveform of a spike before the sample of the peak. nbSamplesAfter number of samples contained in the waveform of a spike after the sample of the peak. active true if the view is the active one, false otherwise.
Referenced by TraceWidget::updateWaveformInformation.
void TraceView::samplingRateModified(long long length)
Updates the length of the document due to a modification of the sampling rate.
length the newly computed length of the document.
References TracesProvider::getSamplingRate.
void TraceView::updateClusterData(bool active)
Updates the cluster information presented on the display.
active true if the view is the active one, false otherwise.
Referenced by TraceWidget::updateClusterData, updateDrawing.
void TraceView::updateClusters(QString name, QValueList< int > &clustersToShow, ItemColors *clusterColors, bool active)
Updates the display due to modification of clusters provided by the cluster provider identified by name.
name name use to identified the cluster provider containing the clusters to show. clustersToShow new list of clusters to be shown. clusterColors list of colors for the clusters. active true if the view is the active one, false otherwise.
Referenced by TraceWidget::updateClusters.
void TraceView::dataAvailable(Array< dataType > &data, QObject *initiator)
Displays the data that has been retrieved.
data array of data (number of channels X number of samples). initiator instance requesting the data.
void TraceView::dataAvailable(Array< dataType > &data, QObject *initiator, QString providerName)
Displays the cluster information that has been retrieved.
data 2 line array containing the sample index of the peak index of each spike existing in the requested time frame with the corresponding cluster id. The first line contains the sample index and the second line the cluster id. initiator instance requesting the data. providerName name of the instance providing the data.
void TraceView::dataAvailable(Array< dataType > &times, Array< int > &ids, QObject *initiator, QString providerName)
Displays the event information that has been retrieved.
times 1 line array containing the time (in recording samples) of each event existing in the requested time frame. ids 1 line array containing the identifiers of each event existing in the requested time frame. initiator instance requesting the data. providerName name of the instance providing the data.
void TraceView::nextClusterDataAvailable(Array< dataType > &data, QObject *initiator, QString providerName, long startingTime, long startingTimeInRecordingUnits)
Compute the cluster information that has been retrieved regarding the next cluster to display.
data 2 line array containing the sample index of the peak index of each spike existing in the requested time frame with the corresponding cluster id. The first line contains the sample index and the second line the cluster id. initiator instance requesting the data. providerName name of the instance providing the data. startingTime time from which the data have been retreived in milisesonds. startingTimeInRecordingUnits time from which the data have been retrieved in recording units.
void TraceView::previousClusterDataAvailable(Array< dataType > &data, QObject *initiator, QString providerName, long startingTime, long startingTimeInRecordingUnits)
Compute the cluster information that has been retrieved regarding the previous cluster to display.
data 2 line array containing the sample index of the peak index of each spike existing in the requested time frame with the corresponding cluster id. The first line contains the sample index and the second line the cluster id. initiator instance requesting the data. providerName name of the instance providing the data. startingTime time from which the data have been retreived in milisesonds. startingTimeInRecordingUnits time from which the data have been retrieved in recording units.
void TraceView::nextEventDataAvailable(Array< dataType > &times, Array< int > &ids, QObject *initiator, QString providerName, long startingTime)
Compute the event information that has been retrieved regarding the next event to display.
times 1 line array containing the time (in recording samples) of each event existing in the requested time frame. ids 1 line array containing the identifiers of each event existing in the requested time frame. initiator instance requesting the data. providerName name of the instance providing the data. startingTime time from which the data have been retreived.
void TraceView::previousEventDataAvailable(Array< dataType > &times, Array< int > &ids, QObject *initiator, QString providerName, long startingTime)
Compute the event information that has been retrieved regarding the previous event to display.
times 1 line array containing the time (in recording samples) of each event existing in the requested time frame. ids 1 line array containing the identifiers of each event existing in the requested time frame. initiator instance requesting the data. providerName name of the instance providing the data. startingTime time from which the data have been retreived.
void TraceView::eventToAddProperties(QString providerName, QString eventDescription)
Stores the properties for the next event to be added.
providerName name use to identified the event provider which will contain the added event. eventDescription description of the next event to be created.
Referenced by TraceWidget::eventToAddProperties.
void TraceView::skipStatusChanged(const QValueList< int > &skippedChannels)
Updates the list of skipped channels.
skippedChannels list of skipped channels
Referenced by TraceWidget::updateSkipStatus.
void TraceView::channelsSelected(const QValueList< int > &selectedIds)
void TraceView::setStartAndDuration(long time, long duration)
void TraceView::eventModified(QString providerName, int selectedEventId, double time, double newTime)
void TraceView::eventRemoved(QString providerName, int selectedEventId, double time)
void TraceView::eventAdded(QString providerName, QString addedEventDescription, double time)
void TraceView::drawContents(QPainter *painter)
Draws the contents of the frame.
painter painter used to draw the contents
void TraceView::mouseMoveEvent(QMouseEvent *event)
The view responds to a mouse move event.
The time is display in the status bar. event mouse move event.
void TraceView::resizeEvent(QResizeEvent *event)
The view responds to a resize event.
The window is recomputed. event resize event.
References BaseFrame::drawContentsMode.
void TraceView::mousePressEvent(QMouseEvent *event)
The view responds to a mouse click.
event mouse release event.
void TraceView::mouseReleaseEvent(QMouseEvent *event)
The view responds to a mouse release.
event mouse event.
void TraceView::mouseDoubleClickEvent(QMouseEvent *event)
The view responds to a double click.
event mouse event.
void TraceView::updateWindow()
Updates the dimension of the window.
void TraceView::updateShownGroupsChannels(const QValueList< int > &channelsToShow)
Updates shownGroupsChannels.
channelsToShow list of channels to shown in the display.
void TraceView::drawTraces(QPainter &painter)
Draws the traces.
painter painter on which to draw the traces.
void TraceView::drawTraces(QValueList< int > channels, bool highlight)
Draws the traces for a subset of channels.
channels list of channels to draw. highlight true if the channels have to be highlighted, false otherwise.
void TraceView::drawTrace(QPainter &painter, int limit, int basePosition, int X, int channelId, int nbSamplesToDraw, bool mouseMoveEvent=false)
Draws the trace for the channel channelId.
painter painter on which to draw the traces. limit the number of pixels in the world beneath which only one pixel is drawn in the viewport. basePosition the base ordinate for the trace to be drawn. X the starting abscissa. channelId the id of the channel for which the trace has to be drawn. nbSamplesToDraw number of samples to draw for the trace. mouseMoveEvent true if the function has been called from the mouseMoveEvent function. In that case no waveforms are drawn even if requested.
void TraceView::drawChannelIdsAndGain(QPainter &painter)
Draws on the left side the id and the amplitude for each channel.
painter painter on which to draw the information.
void TraceView::computeChannelDisplayGain()
Computes the channelDisplayGains.
void TraceView::computeChannelDisplayGain(const QValueList< int > &selectedChannels)
Computes the channelDisplayGains for the selected channels.
selectedChannels ids of the selected channels.
void TraceView::drawCalibrationScale(QPainter &painter)
Draw the calibration scale.
painter painter on which to draw the information.
void TraceView::correctZoom(QRect &r)
Corrects the window due to a zoom.
r rectangle corresponding to the window.
void TraceView::drawEvent(QString providerName, int selectedEventId, dataType selectedEventIndex, bool highlight)
Draws a single event.
providerName name of the instance providing the data for the event to draw. selectedEventId id of the event to draw. selectedEventIndex index of the event to draw. highlight true if the event has to be highlighted, false otherwise.
void TraceView::drawTimeLine(int x, bool initialLine, bool eraseLine=false)
Draws a vertical line at the cursor position.
If the traces are displayed on multiple columns, a line is drawn in each column. x abscissa of the cursor. initialLine true if the line is drawn for the first time, false otherwise. eraseLine true if the line has to be erase and not redraw.