BaseFrame
@0
typedef int BaseFrame::Mode
typedef indicating in wich mode the user is.
DrawContentsMode
const int BaseFrame::MIN_SIZE
const int BaseFrame::MAX_SIZE
const int BaseFrame::BORDER
const int BaseFrame::WINDOW_TOP_LEFT
const int BaseFrame::WINDOW_BOTTOM_RIGHT
QSize BaseFrame::oldSize
QRect BaseFrame::viewport
ZoomWindow BaseFrame::window
Object enabling to transform the window which represent the part of the world to be drawn.
Referenced by viewportToWorldHeight, viewportToWorldWidth, worldToViewportHeight, worldToViewportWidth.
QPoint BaseFrame::firstClick
Coordinates of the point where the user has first click.
bool BaseFrame::isDoubleClick
Boolean indicating that the user has double clicked.
QRect* BaseFrame::rubber
Rectangle identifying the selected area.
DrawContentsMode BaseFrame::drawContentsMode
Mode giving the way of drawing the contents of the view.
Referenced by ClusterView::emptySelection, TraceView::groupColorUpdate, TraceView::resizeEvent, WaveformView::setChannelPositions, WaveformView::setGain, TraceView::setMode, TraceView::showCalibration, TraceView::updateDrawing.
Mode BaseFrame::mode
Draw mode (selected by the user via a menu, a button or a shortcut).
Referenced by TraceView::setMode, setMode.
QCursor BaseFrame::zoomCursor
A cursor to represent the zoom state.
Referenced by TraceView::setMode.
int BaseFrame::Xborder
Border on the left and right sides inside the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget).
Referenced by setBorders.
int BaseFrame::Yborder
Border on the top and bottom sides inside the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget).
Referenced by setBorders.
bool BaseFrame::isRubberBandToBeDrawn
Boolean indicating if a rubber band has to be drawn while not in ZOOM mode, the default is false.
Referenced by drawRubberBand.
bool BaseFrame::wholeHeightRectangle
Boolean indicating if while not in ZOOM mode, the rubber band has to be drawn on whole the height of the window.
The default is no.
Referenced by drawRubberBand.
QColor BaseFrame::colorLegend
Color use to display the legends.
BaseFrame::BaseFrame(int Xborder, int Yborder, QWidget *parent=0, const char *name=0, QColor backgroundColor=Qt::black, int minSize=500, int maxSize=4000, int windowTopLeft=-500, int windowBottomRight=1001, int border=0)
Constructs the view.
Xborder border on the left and right sides inside the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget). Yborder border on the top and bottom sides inside the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget). parent the parent QWidget. name name of the widget (can be used for introspection). backgroundColor color used as background. Balck is the default. minSize minumum size of the view. maxSize maximum size of the view. windowTopLeft the top-left corner of the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget). windowBottomRight bottom-right corner of the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget). border size of the border between the frame and the contents.
BaseFrame::~BaseFrame()
virtual void BaseFrame::willBeKilled()
Signals that the widget is about to be deleted.
void BaseFrame::setBorders(int x, int y)
Sets the borders of the frame.
x border on the left and right sides inside the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget). y border on the top and bottom sides inside the window (QRect corresponding to the part of the drawing which will actually be drawn onto the widget).
References Xborder, Yborder.
virtual void BaseFrame::updateDrawing()
Update the information presented in the view if need it.
virtual void BaseFrame::dockBeingClosed()
void BaseFrame::changeBackgroundColor(QColor color)
virtual void BaseFrame::setMode(BaseFrame::Mode selectedMode)
Change the current mode, call by a selection of a tool.
selectedMode new mode of drawing.
References mode.
void BaseFrame::parentDockBeingClosed(QWidget *viewWidget)
virtual void BaseFrame::drawContents(QPainter *p)=0
Draws the contents of the frame.
p painter used to draw the contents
void BaseFrame::resizeEvent(QResizeEvent *event)
The view responds to a resize event.
event resize event.
Referenced by ErrorMatrixView::resizeEvent, ClusterView::resizeEvent.
void BaseFrame::mousePressEvent(QMouseEvent *event)
The view responds to a mouse click.
event mouse release event.
void BaseFrame::mouseReleaseEvent(QMouseEvent *event)
The view responds to a mouse release.
event mouse event.
void BaseFrame::mouseMoveEvent(QMouseEvent *event)
The view responds to a mouse move.
event mouse event.
void BaseFrame::mouseDoubleClickEvent(QMouseEvent *event)
The view responds to a double click.
event mouse event.
Referenced by ClusterView::mouseDoubleClickEvent.
QPoint BaseFrame::viewportToWorld(int vx, int vy)
Translates a point (vx, vy) on the viewport to a QPoint in the world.
vx x coordinate of the point in the viewport's coordinates system (relative to the widget). vy y coordinate of the point in the viewport's coordinates system (relative to the widget). the point on the viewport translated to a point in the world.
Referenced by viewportToWorld.
QPoint BaseFrame::viewportToWorld(const QPoint &point)
This is an overloaded member function, provided for convenience.
It behaves essentially like the above function. point point with coordinates relative to the widget (viewport). the point on the viewport translated to a point in the world.
References viewportToWorld.
QPoint BaseFrame::worldToViewport(int wx, int wy)
Translates a point (wx, wy) in the world to a QPoint on the viewport (relative to the widget).
wx x coordinate of the point in the world's coordinates system. wy y coordinate of the point in the world's coordinates system. the point on the world translated to a point in the viewport.
Referenced by worldToViewport.
QPoint BaseFrame::worldToViewport(const QPoint &point)
This is an overloaded member function, provided for convenience.
It behaves essentially like the above function. point point with coordinates in the world. the point on the world translated to a point in the viewport.
References worldToViewport.
long BaseFrame::worldToViewportAbscissa(long wx)
Translates the abscissa wx in the world to the abscissa on the viewport (relative to the widget).
wx abscissa in the world's coordinates system. abscissa in the viewport's coordinates system.
long BaseFrame::worldToViewportOrdinate(long wy)
Translates the abscissa wy in the world to the abscissa on the viewport (relative to the widget).
wy ordinate in the world's coordinates system. ordinate in the viewport's coordinates system.
void BaseFrame::drawRubber()
Draws the rectangle specifying the select area.
long BaseFrame::worldToViewportWidth(long width)
Translates the width width in the world to a width on the viewport (relative to the widget).
width width in the world's coordinates system. width in the viewport's coordinates system.
References window.
long BaseFrame::worldToViewportHeight(long height)
Translates the height height in the world to a height on the viewport (relative to the widget).
height height in the world's coordinates system. height in the viewport's coordinates system.
References window.
long BaseFrame::viewportToWorldWidth(long width)
Translates the width width on the viewport (relative to the widget) to a width in the world.
width width in the world's coordinates system. width in the viewport's coordinates system.
References window.
long BaseFrame::viewportToWorldHeight(long height)
Translates the height height on the viewport (relative to the widget) to a height in the world.
height height in the world's coordinates system. height in the viewport's coordinates system.
References window.
void BaseFrame::drawRubberBand(bool draw, bool vertical=false)
Sets if a rubber band has to be drawn while the mode is not ZOOM, and how it sould be drawn.
draw true if a rubber band has to be drawn, false otherwise. vertical true if the rubber band has to be drawn on whole the height of the window, false otherwise.
References isRubberBandToBeDrawn, wholeHeightRectangle.
Referenced by TraceView::setMode.